// Jevxo Admin Panel - Mock Data

// ===== DASHBOARD =====
export const dashboardStats = {
  totalIncome: 284500,
  totalExpenses: 142300,
  totalClients: 1248,
  totalMembers: 86,
  totalProjects: 342,
  totalServices: 28,
  totalProducts: 156,
  totalInvestments: 52000,
  monthlyIncome: [
    { month: "Jan", income: 18500, expenses: 12000 },
    { month: "Feb", income: 22000, expenses: 14500 },
    { month: "Mar", income: 19800, expenses: 11200 },
    { month: "Apr", income: 28400, expenses: 16800 },
    { month: "May", income: 32100, expenses: 18900 },
    { month: "Jun", income: 26700, expenses: 15400 },
    { month: "Jul", income: 31200, expenses: 17600 },
    { month: "Aug", income: 27800, expenses: 14200 },
    { month: "Sep", income: 24600, expenses: 13100 },
    { month: "Oct", income: 29400, expenses: 16500 },
    { month: "Nov", income: 33000, expenses: 19200 },
    { month: "Dec", income: 35000, expenses: 20100 },
  ],
  salesByCategory: [
    { name: "Web Development", value: 35 },
    { name: "Mobile Apps", value: 25 },
    { name: "UI/UX Design", value: 20 },
    { name: "Marketing", value: 12 },
    { name: "Consulting", value: 8 },
  ],
  recentActivities: [
    {
      id: 1,
      action: "New client registered",
      user: "Ahmed Khan",
      time: "5 min ago",
      type: "client",
    },
    {
      id: 2,
      action: "Invoice #1042 paid",
      user: "TechCorp Ltd",
      time: "12 min ago",
      type: "invoice",
    },
    {
      id: 3,
      action: "Project milestone completed",
      user: "Sarah Ali",
      time: "30 min ago",
      type: "project",
    },
    {
      id: 4,
      action: "New support ticket",
      user: "Global Systems",
      time: "1 hr ago",
      type: "ticket",
    },
    {
      id: 5,
      action: "Staff member added",
      user: "Ali Raza",
      time: "2 hrs ago",
      type: "team",
    },
    {
      id: 6,
      action: "Service package updated",
      user: "Admin",
      time: "3 hrs ago",
      type: "service",
    },
  ],
};

// ===== BLOG / CMS =====
export const blogPosts = [
  {
    id: 1,
    title: "Getting Started with Enterprise SaaS",
    category: "Technology",
    author: "Ahmed Khan",
    status: "Published",
    date: "2025-12-01",
    views: 1240,
  },
  {
    id: 2,
    title: "Top 10 Business Strategies for 2026",
    category: "Business",
    author: "Sarah Ali",
    status: "Draft",
    date: "2025-12-05",
    views: 0,
  },
  {
    id: 3,
    title: "How CRM Boosts Your Revenue",
    category: "Marketing",
    author: "Usman Tariq",
    status: "Published",
    date: "2025-11-28",
    views: 890,
  },
  {
    id: 4,
    title: "Employee Engagement Best Practices",
    category: "HR",
    author: "Fatima Noor",
    status: "Published",
    date: "2025-11-20",
    views: 567,
  },
  {
    id: 5,
    title: "Understanding Cloud Infrastructure",
    category: "Technology",
    author: "Ahmed Khan",
    status: "Under Review",
    date: "2025-12-08",
    views: 0,
  },
  {
    id: 6,
    title: "Financial Planning for Startups",
    category: "Finance",
    author: "Bilal Ahmed",
    status: "Published",
    date: "2025-11-15",
    views: 1102,
  },
];

export const blogCategories = [
  { id: 1, name: "Technology", posts: 24 },
  { id: 2, name: "Business", posts: 18 },
  { id: 3, name: "Marketing", posts: 15 },
  { id: 4, name: "HR", posts: 9 },
  { id: 5, name: "Finance", posts: 12 },
];

// ===== PROJECTS =====
export const projects = [
  {
    id: 1,
    name: "E-Commerce Platform",
    client: "TechCorp Ltd",
    status: "In Progress",
    priority: "High",
    progress: 72,
    budget: 45000,
    startDate: "2025-09-01",
    deadline: "2026-03-15",
    assignedTo: "Team Alpha",
  },
  {
    id: 2,
    name: "CRM Integration",
    client: "Global Systems",
    status: "In Progress",
    priority: "Medium",
    progress: 45,
    budget: 28000,
    startDate: "2025-10-15",
    deadline: "2026-02-28",
    assignedTo: "Team Beta",
  },
  {
    id: 3,
    name: "Mobile Banking App",
    client: "FinTech Solutions",
    status: "Pending",
    priority: "High",
    progress: 0,
    budget: 65000,
    startDate: "2026-01-01",
    deadline: "2026-06-30",
    assignedTo: "Team Alpha",
  },
  {
    id: 4,
    name: "HR Portal Redesign",
    client: "MegaCorp Inc",
    status: "Completed",
    priority: "Low",
    progress: 100,
    budget: 18000,
    startDate: "2025-07-01",
    deadline: "2025-11-30",
    assignedTo: "Team Gamma",
  },
  {
    id: 5,
    name: "Analytics Dashboard",
    client: "DataDriven Co",
    status: "In Progress",
    priority: "High",
    progress: 88,
    budget: 32000,
    startDate: "2025-08-15",
    deadline: "2026-01-31",
    assignedTo: "Team Beta",
  },
  {
    id: 6,
    name: "Marketing Website",
    client: "StartUp Hub",
    status: "Rejected",
    priority: "Low",
    progress: 0,
    budget: 12000,
    startDate: "",
    deadline: "",
    assignedTo: "",
  },
  {
    id: 7,
    name: "Inventory System",
    client: "RetailMax",
    status: "In Progress",
    priority: "Medium",
    progress: 35,
    budget: 22000,
    startDate: "2025-11-01",
    deadline: "2026-04-15",
    assignedTo: "Team Gamma",
  },
  {
    id: 8,
    name: "School Management App",
    client: "EduTech Academy",
    status: "Pending",
    priority: "Medium",
    progress: 0,
    budget: 38000,
    startDate: "2026-02-01",
    deadline: "2026-08-30",
    assignedTo: "Team Alpha",
  },
];

// ===== SERVICES =====
export const services = [
  {
    id: 1,
    name: "Web Development",
    category: "Development",
    price: 5000,
    status: "Active",
    clients: 45,
    description: "Full-stack web application development",
  },
  {
    id: 2,
    name: "Mobile App Development",
    category: "Development",
    price: 8000,
    status: "Active",
    clients: 32,
    description: "iOS and Android app development",
  },
  {
    id: 3,
    name: "UI/UX Design",
    category: "Design",
    price: 3000,
    status: "Active",
    clients: 56,
    description: "User interface and experience design",
  },
  {
    id: 4,
    name: "SEO Optimization",
    category: "Marketing",
    price: 1500,
    status: "Active",
    clients: 78,
    description: "Search engine optimization services",
  },
  {
    id: 5,
    name: "Cloud Hosting",
    category: "Infrastructure",
    price: 500,
    status: "Active",
    clients: 120,
    description: "Managed cloud hosting solutions",
  },
  {
    id: 6,
    name: "IT Consulting",
    category: "Consulting",
    price: 2500,
    status: "Active",
    clients: 28,
    description: "Technology strategy consulting",
  },
  {
    id: 7,
    name: "Data Analytics",
    category: "Analytics",
    price: 4000,
    status: "Inactive",
    clients: 15,
    description: "Business intelligence and analytics",
  },
  {
    id: 8,
    name: "Cybersecurity Audit",
    category: "Security",
    price: 6000,
    status: "Active",
    clients: 22,
    description: "Security assessment and audit",
  },
];

// ===== TEAM / STAFF =====
export const teamMembers = [
  {
    id: 1,
    name: "Ahmed Khan",
    role: "Lead Developer",
    department: "Engineering",
    email: "ahmed@jevxo.com",
    phone: "+92 300 1234567",
    status: "Active",
    joinDate: "2023-01-15",
    performance: 95,
    avatar: "AK",
  },
  {
    id: 2,
    name: "Sarah Ali",
    role: "Project Manager",
    department: "Management",
    email: "sarah@jevxo.com",
    phone: "+92 301 2345678",
    status: "Active",
    joinDate: "2023-03-01",
    performance: 92,
    avatar: "SA",
  },
  {
    id: 3,
    name: "Usman Tariq",
    role: "Marketing Manager",
    department: "Marketing",
    email: "usman@jevxo.com",
    phone: "+92 302 3456789",
    status: "Active",
    joinDate: "2023-06-15",
    performance: 88,
    avatar: "UT",
  },
  {
    id: 4,
    name: "Fatima Noor",
    role: "HR Manager",
    department: "Human Resources",
    email: "fatima@jevxo.com",
    phone: "+92 303 4567890",
    status: "Active",
    joinDate: "2023-02-01",
    performance: 91,
    avatar: "FN",
  },
  {
    id: 5,
    name: "Bilal Ahmed",
    role: "Finance Manager",
    department: "Finance",
    email: "bilal@jevxo.com",
    phone: "+92 304 5678901",
    status: "Active",
    joinDate: "2023-04-10",
    performance: 87,
    avatar: "BA",
  },
  {
    id: 6,
    name: "Ali Raza",
    role: "Frontend Developer",
    department: "Engineering",
    email: "ali@jevxo.com",
    phone: "+92 305 6789012",
    status: "Active",
    joinDate: "2024-01-15",
    performance: 84,
    avatar: "AR",
  },
  {
    id: 7,
    name: "Hina Shahid",
    role: "UI/UX Designer",
    department: "Design",
    email: "hina@jevxo.com",
    phone: "+92 306 7890123",
    status: "On Leave",
    joinDate: "2023-08-20",
    performance: 90,
    avatar: "HS",
  },
  {
    id: 8,
    name: "Zain Malik",
    role: "Backend Developer",
    department: "Engineering",
    email: "zain@jevxo.com",
    phone: "+92 307 8901234",
    status: "Active",
    joinDate: "2024-03-01",
    performance: 82,
    avatar: "ZM",
  },
];

// ===== TASKS =====
export const tasks = [
  {
    id: 1,
    title: "Design homepage mockup",
    status: "Completed",
    priority: "High",
    assignee: "Hina Shahid",
    project: "Marketing Website",
    dueDate: "2025-12-10",
    category: "Design",
  },
  {
    id: 2,
    title: "Implement user authentication",
    status: "In Progress",
    priority: "High",
    assignee: "Ahmed Khan",
    project: "E-Commerce Platform",
    dueDate: "2025-12-15",
    category: "Development",
  },
  {
    id: 3,
    title: "Write API documentation",
    status: "Todo",
    priority: "Medium",
    assignee: "Zain Malik",
    project: "CRM Integration",
    dueDate: "2025-12-20",
    category: "Documentation",
  },
  {
    id: 4,
    title: "Setup CI/CD pipeline",
    status: "In Progress",
    priority: "High",
    assignee: "Ali Raza",
    project: "Analytics Dashboard",
    dueDate: "2025-12-12",
    category: "DevOps",
  },
  {
    id: 5,
    title: "Database schema design",
    status: "Completed",
    priority: "High",
    assignee: "Zain Malik",
    project: "Mobile Banking App",
    dueDate: "2025-12-08",
    category: "Development",
  },
  {
    id: 6,
    title: "Client feedback review",
    status: "Todo",
    priority: "Low",
    assignee: "Sarah Ali",
    project: "HR Portal Redesign",
    dueDate: "2025-12-18",
    category: "Review",
  },
  {
    id: 7,
    title: "Performance optimization",
    status: "In Progress",
    priority: "Medium",
    assignee: "Ahmed Khan",
    project: "Analytics Dashboard",
    dueDate: "2025-12-22",
    category: "Development",
  },
  {
    id: 8,
    title: "Create marketing materials",
    status: "Todo",
    priority: "Medium",
    assignee: "Usman Tariq",
    project: "Marketing Website",
    dueDate: "2025-12-25",
    category: "Marketing",
  },
  {
    id: 9,
    title: "Security audit report",
    status: "Todo",
    priority: "High",
    assignee: "Ahmed Khan",
    project: "E-Commerce Platform",
    dueDate: "2025-12-28",
    category: "Security",
  },
  {
    id: 10,
    title: "Unit test coverage",
    status: "In Progress",
    priority: "Medium",
    assignee: "Ali Raza",
    project: "CRM Integration",
    dueDate: "2025-12-16",
    category: "Testing",
  },
];

// ===== CLIENTS =====
export const clients = [
  {
    id: 1,
    name: "TechCorp Ltd",
    email: "contact@techcorp.com",
    phone: "+92 21 1234567",
    status: "Active",
    projects: 3,
    totalSpent: 125000,
    joinDate: "2024-01-10",
    industry: "Technology",
  },
  {
    id: 2,
    name: "Global Systems",
    email: "info@globalsystems.com",
    phone: "+92 42 2345678",
    status: "Active",
    projects: 2,
    totalSpent: 85000,
    joinDate: "2024-03-15",
    industry: "IT Services",
  },
  {
    id: 3,
    name: "FinTech Solutions",
    email: "hello@fintech.com",
    phone: "+92 51 3456789",
    status: "Active",
    projects: 1,
    totalSpent: 65000,
    joinDate: "2024-06-20",
    industry: "Finance",
  },
  {
    id: 4,
    name: "MegaCorp Inc",
    email: "support@megacorp.com",
    phone: "+92 21 4567890",
    status: "Active",
    projects: 2,
    totalSpent: 48000,
    joinDate: "2024-02-01",
    industry: "Enterprise",
  },
  {
    id: 5,
    name: "DataDriven Co",
    email: "team@datadriven.com",
    phone: "+92 42 5678901",
    status: "Active",
    projects: 1,
    totalSpent: 32000,
    joinDate: "2024-07-10",
    industry: "Analytics",
  },
  {
    id: 6,
    name: "StartUp Hub",
    email: "admin@startuphub.com",
    phone: "+92 51 6789012",
    status: "Blocked",
    projects: 0,
    totalSpent: 8000,
    joinDate: "2024-09-01",
    industry: "Incubator",
  },
  {
    id: 7,
    name: "RetailMax",
    email: "ops@retailmax.com",
    phone: "+92 21 7890123",
    status: "Active",
    projects: 1,
    totalSpent: 22000,
    joinDate: "2024-08-15",
    industry: "Retail",
  },
  {
    id: 8,
    name: "EduTech Academy",
    email: "info@edutech.com",
    phone: "+92 42 8901234",
    status: "Active",
    projects: 1,
    totalSpent: 38000,
    joinDate: "2024-10-01",
    industry: "Education",
  },
];

export const students = [
  {
    id: 1,
    name: "Ayesha Rahman",
    email: "ayesha.rahman@studentmail.com",
    phone: "+880 1712 345678",
    status: "Active",
    courses: 3,
    totalFees: 45000,
    joinDate: "2024-01-12",
    department: "Computer Science",
  },
  {
    id: 2,
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@studentmail.com",
    phone: "+880 1812 456789",
    status: "Active",
    courses: 2,
    totalFees: 30000,
    joinDate: "2024-02-20",
    department: "Business Administration",
  },
  {
    id: 3,
    name: "Nusrat Jahan",
    email: "nusrat.jahan@studentmail.com",
    phone: "+880 1912 567890",
    status: "Inactive",
    courses: 1,
    totalFees: 15000,
    joinDate: "2024-03-05",
    department: "Mathematics",
  },
  {
    id: 4,
    name: "Sabbir Hossain",
    email: "sabbir.hossain@studentmail.com",
    phone: "+880 1612 678901",
    status: "Active",
    courses: 4,
    totalFees: 60000,
    joinDate: "2024-01-25",
    department: "Software Engineering",
  },
  {
    id: 5,
    name: "Mim Akter",
    email: "mim.akter@studentmail.com",
    phone: "+880 1512 789012",
    status: "Active",
    courses: 2,
    totalFees: 28000,
    joinDate: "2024-04-18",
    department: "Marketing",
  },
  {
    id: 6,
    name: "Rafiul Karim",
    email: "rafiul.karim@studentmail.com",
    phone: "+880 1713 890123",
    status: "Blocked",
    courses: 0,
    totalFees: 5000,
    joinDate: "2024-05-10",
    department: "Accounting",
  },
  {
    id: 7,
    name: "Farzana Islam",
    email: "farzana.islam@studentmail.com",
    phone: "+880 1813 901234",
    status: "Active",
    courses: 3,
    totalFees: 42000,
    joinDate: "2024-06-22",
    department: "Data Science",
  },
  {
    id: 8,
    name: "Imran Chowdhury",
    email: "imran.chowdhury@studentmail.com",
    phone: "+880 1913 012345",
    status: "Active",
    courses: 1,
    totalFees: 18000,
    joinDate: "2024-07-30",
    department: "Cyber Security",
  },
];

// ===== INVOICES =====
export const invoices = [
  {
    id: 1001,
    client: "TechCorp Ltd",
    amount: 15000,
    tax: 1500,
    discount: 500,
    status: "Paid",
    date: "2025-12-01",
    dueDate: "2025-12-15",
    items: 3,
  },
  {
    id: 1002,
    client: "Global Systems",
    amount: 8500,
    tax: 850,
    discount: 0,
    status: "Pending",
    date: "2025-12-05",
    dueDate: "2025-12-20",
    items: 2,
  },
  {
    id: 1003,
    client: "FinTech Solutions",
    amount: 22000,
    tax: 2200,
    discount: 1000,
    status: "Pending",
    date: "2025-12-08",
    dueDate: "2025-12-22",
    items: 5,
  },
  {
    id: 1004,
    client: "MegaCorp Inc",
    amount: 6000,
    tax: 600,
    discount: 0,
    status: "Paid",
    date: "2025-11-25",
    dueDate: "2025-12-10",
    items: 2,
  },
  {
    id: 1005,
    client: "DataDriven Co",
    amount: 12500,
    tax: 1250,
    discount: 500,
    status: "Overdue",
    date: "2025-11-15",
    dueDate: "2025-11-30",
    items: 4,
  },
  {
    id: 1006,
    client: "RetailMax",
    amount: 9800,
    tax: 980,
    discount: 0,
    status: "Cancelled",
    date: "2025-11-20",
    dueDate: "2025-12-05",
    items: 3,
  },
  {
    id: 1007,
    client: "EduTech Academy",
    amount: 18500,
    tax: 1850,
    discount: 750,
    status: "Paid",
    date: "2025-12-02",
    dueDate: "2025-12-16",
    items: 4,
  },
  {
    id: 1008,
    client: "TechCorp Ltd",
    amount: 28000,
    tax: 2800,
    discount: 1500,
    status: "Pending",
    date: "2025-12-10",
    dueDate: "2025-12-25",
    items: 6,
  },
];

// ===== MARKETING =====
export const marketingCampaigns = [
  {
    id: 1,
    name: "Winter Sale 2025",
    type: "Email",
    status: "Active",
    sent: 4500,
    opened: 2100,
    clicked: 890,
    date: "2025-12-01",
  },
  {
    id: 2,
    name: "New Year Promo",
    type: "SMS",
    status: "Scheduled",
    sent: 0,
    opened: 0,
    clicked: 0,
    date: "2025-12-28",
  },
  {
    id: 3,
    name: "Product Launch",
    type: "Push",
    status: "Completed",
    sent: 8200,
    opened: 5400,
    clicked: 2300,
    date: "2025-11-15",
  },
  {
    id: 4,
    name: "Black Friday Deal",
    type: "Email",
    status: "Completed",
    sent: 12000,
    opened: 7800,
    clicked: 4200,
    date: "2025-11-28",
  },
  {
    id: 5,
    name: "Holiday Greetings",
    type: "Email",
    status: "Draft",
    sent: 0,
    opened: 0,
    clicked: 0,
    date: "2025-12-20",
  },
  {
    id: 6,
    name: "Flash Sale Alert",
    type: "SMS",
    status: "Active",
    sent: 3200,
    opened: 0,
    clicked: 0,
    date: "2025-12-05",
  },
];

// ===== ROLES =====
export const roles = [
  {
    id: 1,
    name: "Super Admin",
    users: 2,
    permissions: "Full Access",
    description: "Complete system control",
  },
  {
    id: 2,
    name: "CRM Manager",
    users: 4,
    permissions: "CRM, Clients, Marketing",
    description: "Customer relationship management",
  },
  {
    id: 3,
    name: "HR Manager",
    users: 3,
    permissions: "HRM, Team, Attendance",
    description: "Human resource management",
  },
  {
    id: 4,
    name: "Admin",
    users: 12,
    permissions:
      "Dashboard, Projects, Tasks, Invoice Operations, Profile, Reports",
    description: "Day-to-day operations",
  },
  {
    id: 5,
    name: "Staff",
    users: 3,
    permissions: "Limited permissions",
    description: "Staff",
  },
  {
    id: 6,
    name: "Client",
    users: 5,
    permissions: "Limited permissions",
    description: "Client",
  },
  {
    id: 7,
    name: "Users",
    users: 6,
    permissions: "Projects, Tasks, Teams",
    description: "Project oversight",
  },
];

export const permissionModules = [
  "Dashboard",
  "CMS",
  "Projects",
  "Services",
  "Team",
  "Tasks",
  "Clients",
  "Invoices",
  "Marketing",
  "Roles",
  "Partnership",
  "Schools",
  "Settings",
  "Support",
  "Reports",
];

// ===== PARTNERSHIPS =====
export const partners = [
  {
    id: 1,
    name: "DigiMarketing Pro",
    type: "Referral",
    status: "Active",
    commission: 15,
    totalRevenue: 45000,
    joinDate: "2024-05-01",
  },
  {
    id: 2,
    name: "CloudHost Solutions",
    type: "Revenue Share",
    status: "Active",
    commission: 20,
    totalRevenue: 62000,
    joinDate: "2024-03-15",
  },
  {
    id: 3,
    name: "DesignStudio Co",
    type: "Referral",
    status: "Active",
    commission: 10,
    totalRevenue: 28000,
    joinDate: "2024-07-20",
  },
  {
    id: 4,
    name: "AppDev Alliance",
    type: "Revenue Share",
    status: "Inactive",
    commission: 25,
    totalRevenue: 15000,
    joinDate: "2024-09-01",
  },
  {
    id: 5,
    name: "BizConsult Group",
    type: "Referral",
    status: "Active",
    commission: 12,
    totalRevenue: 35000,
    joinDate: "2024-06-10",
  },
];

// ===== SCHOOLS =====
export const schools = [
  {
    id: 1,
    name: "ABC International School",
    students: 450,
    fees: 125000,
    status: "Active",
    location: "Lahore",
    notices: 3,
    marketingCharges: 5000,
  },
  {
    id: 2,
    name: "XYZ Grammar School",
    students: 320,
    fees: 85000,
    status: "Active",
    location: "Karachi",
    notices: 1,
    marketingCharges: 3500,
  },
  {
    id: 3,
    name: "Elite Academy",
    students: 280,
    fees: 95000,
    status: "Active",
    location: "Islamabad",
    notices: 2,
    marketingCharges: 4000,
  },
  {
    id: 4,
    name: "Star Public School",
    students: 520,
    fees: 68000,
    status: "Pending",
    location: "Rawalpindi",
    notices: 0,
    marketingCharges: 0,
  },
  {
    id: 5,
    name: "Modern Learning Center",
    students: 180,
    fees: 110000,
    status: "Active",
    location: "Faisalabad",
    notices: 4,
    marketingCharges: 6000,
  },
];

// ===== SUPPORT TICKETS =====
export const supportTickets = [
  {
    id: 1,
    subject: "Login issues after update",
    client: "TechCorp Ltd",
    priority: "High",
    status: "Open",
    assignee: "Ahmed Khan",
    date: "2025-12-10",
    category: "Technical",
  },
  {
    id: 2,
    subject: "Invoice not generating PDF",
    client: "Global Systems",
    priority: "Medium",
    status: "In Progress",
    assignee: "Ali Raza",
    date: "2025-12-09",
    category: "Bug",
  },
  {
    id: 3,
    subject: "Need API documentation",
    client: "FinTech Solutions",
    priority: "Low",
    status: "Open",
    assignee: "Zain Malik",
    date: "2025-12-08",
    category: "Documentation",
  },
  {
    id: 4,
    subject: "Payment gateway error",
    client: "MegaCorp Inc",
    priority: "High",
    status: "Resolved",
    assignee: "Ahmed Khan",
    date: "2025-12-05",
    category: "Technical",
  },
  {
    id: 5,
    subject: "Feature request: Bulk export",
    client: "DataDriven Co",
    priority: "Medium",
    status: "Open",
    assignee: "Sarah Ali",
    date: "2025-12-07",
    category: "Feature Request",
  },
  {
    id: 6,
    subject: "Dashboard loading slowly",
    client: "RetailMax",
    priority: "Medium",
    status: "In Progress",
    assignee: "Ali Raza",
    date: "2025-12-06",
    category: "Performance",
  },
];

// ===== SUCCESS STORIES =====
export const successStories = [
  {
    id: 1,
    title: "TechCorp Increased Revenue by 200%",
    client: "TechCorp Ltd",
    date: "2025-11-01",
    status: "Published",
    views: 3400,
  },
  {
    id: 2,
    title: "Global Systems Streamlined Operations",
    client: "Global Systems",
    date: "2025-10-15",
    status: "Published",
    views: 2100,
  },
  {
    id: 3,
    title: "FinTech Solutions Digital Transformation",
    client: "FinTech Solutions",
    date: "2025-09-20",
    status: "Draft",
    views: 0,
  },
  {
    id: 4,
    title: "MegaCorp Employee Satisfaction Up 45%",
    client: "MegaCorp Inc",
    date: "2025-08-10",
    status: "Published",
    views: 1800,
  },
];
