// Jevxo Admin Panel - Mock Data

// ===== DASHBOARD =====
export const dashboardStats = {
  totalIncome: 284500,
  totalExpenses: 142300,
  totalClients: 1248,
  totalMembers: 86,
  totalProjects: 342,
  totalServices: 28,
  totalProducts: 156,
  totalInvestments: 52000,
  monthlyIncome: [
    { month: "Jan", income: 18500, expenses: 12000 },
    { month: "Feb", income: 22000, expenses: 14500 },
    { month: "Mar", income: 19800, expenses: 11200 },
    { month: "Apr", income: 28400, expenses: 16800 },
    { month: "May", income: 32100, expenses: 18900 },
    { month: "Jun", income: 26700, expenses: 15400 },
    { month: "Jul", income: 31200, expenses: 17600 },
    { month: "Aug", income: 27800, expenses: 14200 },
    { month: "Sep", income: 24600, expenses: 13100 },
    { month: "Oct", income: 29400, expenses: 16500 },
    { month: "Nov", income: 33000, expenses: 19200 },
    { month: "Dec", income: 35000, expenses: 20100 },
  ],
  salesByCategory: [
    { name: "Web Development", value: 35 },
    { name: "Mobile Apps", value: 25 },
    { name: "UI/UX Design", value: 20 },
    { name: "Marketing", value: 12 },
    { name: "Consulting", value: 8 },
  ],
  recentActivities: [
    {
      id: 1,
      action: "New client registered",
      user: "Ahmed Khan",
      time: "5 min ago",
      type: "client",
    },
    {
      id: 2,
      action: "Invoice #1042 paid",
      user: "TechCorp Ltd",
      time: "12 min ago",
      type: "invoice",
    },
    {
      id: 3,
      action: "Project milestone completed",
      user: "Sarah Ali",
      time: "30 min ago",
      type: "project",
    },
    {
      id: 4,
      action: "New support ticket",
      user: "Global Systems",
      time: "1 hr ago",
      type: "ticket",
    },
    {
      id: 5,
      action: "Staff member added",
      user: "Ali Raza",
      time: "2 hrs ago",
      type: "team",
    },
    {
      id: 6,
      action: "Service package updated",
      user: "Admin",
      time: "3 hrs ago",
      type: "service",
    },
  ],
};

// ===== BLOG / CMS =====
export const blogPosts = [
  {
    id: 1,
    title: "Getting Started with Enterprise SaaS",
    category: "Technology",
    author: "Ahmed Khan",
    status: "Published",
    date: "2025-12-01",
    views: 1240,
  },
  {
    id: 2,
    title: "Top 10 Business Strategies for 2026",
    category: "Business",
    author: "Sarah Ali",
    status: "Draft",
    date: "2025-12-05",
    views: 0,
  },
  {
    id: 3,
    title: "How CRM Boosts Your Revenue",
    category: "Marketing",
    author: "Usman Tariq",
    status: "Published",
    date: "2025-11-28",
    views: 890,
  },
  {
    id: 4,
    title: "Employee Engagement Best Practices",
    category: "HR",
    author: "Fatima Noor",
    status: "Published",
    date: "2025-11-20",
    views: 567,
  },
  {
    id: 5,
    title: "Understanding Cloud Infrastructure",
    category: "Technology",
    author: "Ahmed Khan",
    status: "Under Review",
    date: "2025-12-08",
    views: 0,
  },
  {
    id: 6,
    title: "Financial Planning for Startups",
    category: "Finance",
    author: "Bilal Ahmed",
    status: "Published",
    date: "2025-11-15",
    views: 1102,
  },
];

export const blogCategories = [
  { id: 1, name: "Technology", posts: 24 },
  { id: 2, name: "Business", posts: 18 },
  { id: 3, name: "Marketing", posts: 15 },
  { id: 4, name: "HR", posts: 9 },
  { id: 5, name: "Finance", posts: 12 },
];

// ===== PROJECTS =====
export const projects = [
  {
    id: 1,
    name: "E-Commerce Platform",
    client: "TechCorp Ltd",
    status: "In Progress",
    priority: "High",
    progress: 72,
    budget: 45000,
    startDate: "2025-09-01",
    deadline: "2026-03-15",
    assignedTo: "Team Alpha",
  },
  {
    id: 2,
    name: "CRM Integration",
    client: "Global Systems",
    status: "In Progress",
    priority: "Medium",
    progress: 45,
    budget: 28000,
    startDate: "2025-10-15",
    deadline: "2026-02-28",
    assignedTo: "Team Beta",
  },
  {
    id: 3,
    name: "Mobile Banking App",
    client: "FinTech Solutions",
    status: "Pending",
    priority: "High",
    progress: 0,
    budget: 65000,
    startDate: "2026-01-01",
    deadline: "2026-06-30",
    assignedTo: "Team Alpha",
  },
  {
    id: 4,
    name: "HR Portal Redesign",
    client: "MegaCorp Inc",
    status: "Completed",
    priority: "Low",
    progress: 100,
    budget: 18000,
    startDate: "2025-07-01",
    deadline: "2025-11-30",
    assignedTo: "Team Gamma",
  },
  {
    id: 5,
    name: "Analytics Dashboard",
    client: "DataDriven Co",
    status: "In Progress",
    priority: "High",
    progress: 88,
    budget: 32000,
    startDate: "2025-08-15",
    deadline: "2026-01-31",
    assignedTo: "Team Beta",
  },
  {
    id: 6,
    name: "Marketing Website",
    client: "StartUp Hub",
    status: "Rejected",
    priority: "Low",
    progress: 0,
    budget: 12000,
    startDate: "",
    deadline: "",
    assignedTo: "",
  },
  {
    id: 7,
    name: "Inventory System",
    client: "RetailMax",
    status: "In Progress",
    priority: "Medium",
    progress: 35,
    budget: 22000,
    startDate: "2025-11-01",
    deadline: "2026-04-15",
    assignedTo: "Team Gamma",
  },
  {
    id: 8,
    name: "School Management App",
    client: "EduTech Academy",
    status: "Pending",
    priority: "Medium",
    progress: 0,
    budget: 38000,
    startDate: "2026-02-01",
    deadline: "2026-08-30",
    assignedTo: "Team Alpha",
  },
];

// ===== SERVICES =====
export const services = [
  {
    id: 1,
    name: "Web Development",
    category: "Development",
    price: 5000,
    status: "Active",
    clients: 45,
    description: "Full-stack web application development",
  },
  {
    id: 2,
    name: "Mobile App Development",
    category: "Development",
    price: 8000,
    status: "Active",
    clients: 32,
    description: "iOS and Android app development",
  },
  {
    id: 3,
    name: "UI/UX Design",
    category: "Design",
    price: 3000,
    status: "Active",
    clients: 56,
    description: "User interface and experience design",
  },
  {
    id: 4,
    name: "SEO Optimization",
    category: "Marketing",
    price: 1500,
    status: "Active",
    clients: 78,
    description: "Search engine optimization services",
  },
  {
    id: 5,
    name: "Cloud Hosting",
    category: "Infrastructure",
    price: 500,
    status: "Active",
    clients: 120,
    description: "Managed cloud hosting solutions",
  },
  {
    id: 6,
    name: "IT Consulting",
    category: "Consulting",
    price: 2500,
    status: "Active",
    clients: 28,
    description: "Technology strategy consulting",
  },
  {
    id: 7,
    name: "Data Analytics",
    category: "Analytics",
    price: 4000,
    status: "Inactive",
    clients: 15,
    description: "Business intelligence and analytics",
  },
  {
    id: 8,
    name: "Cybersecurity Audit",
    category: "Security",
    price: 6000,
    status: "Active",
    clients: 22,
    description: "Security assessment and audit",
  },
];

// ===== TEAM / STAFF =====
export const teamMembers = [
  {
    id: 1,
    name: "Ahmed Khan",
    role: "Lead Developer",
    department: "Engineering",
    email: "ahmed@jevxo.com",
    phone: "+92 300 1234567",
    status: "Active",
    joinDate: "2023-01-15",
    performance: 95,
    avatar: "AK",
  },
  {
    id: 2,
    name: "Sarah Ali",
    role: "Project Manager",
    department: "Management",
    email: "sarah@jevxo.com",
    phone: "+92 301 2345678",
    status: "Active",
    joinDate: "2023-03-01",
    performance: 92,
    avatar: "SA",
  },
  {
    id: 3,
    name: "Usman Tariq",
    role: "Marketing Manager",
    department: "Marketing",
    email: "usman@jevxo.com",
    phone: "+92 302 3456789",
    status: "Active",
    joinDate: "2023-06-15",
    performance: 88,
    avatar: "UT",
  },
  {
    id: 4,
    name: "Fatima Noor",
    role: "HR Manager",
    department: "Human Resources",
    email: "fatima@jevxo.com",
    phone: "+92 303 4567890",
    status: "Active",
    joinDate: "2023-02-01",
    performance: 91,
    avatar: "FN",
  },
  {
    id: 5,
    name: "Bilal Ahmed",
    role: "Finance Manager",
    department: "Finance",
    email: "bilal@jevxo.com",
    phone: "+92 304 5678901",
    status: "Active",
    joinDate: "2023-04-10",
    performance: 87,
    avatar: "BA",
  },
  {
    id: 6,
    name: "Ali Raza",
    role: "Frontend Developer",
    department: "Engineering",
    email: "ali@jevxo.com",
    phone: "+92 305 6789012",
    status: "Active",
    joinDate: "2024-01-15",
    performance: 84,
    avatar: "AR",
  },
  {
    id: 7,
    name: "Hina Shahid",
    role: "UI/UX Designer",
    department: "Design",
    email: "hina@jevxo.com",
    phone: "+92 306 7890123",
    status: "On Leave",
    joinDate: "2023-08-20",
    performance: 90,
    avatar: "HS",
  },
  {
    id: 8,
    name: "Zain Malik",
    role: "Backend Developer",
    department: "Engineering",
    email: "zain@jevxo.com",
    phone: "+92 307 8901234",
    status: "Active",
    joinDate: "2024-03-01",
    performance: 82,
    avatar: "ZM",
  },
];

// ===== TASKS =====
export const tasks = [
  {
    id: 1,
    title: "Design homepage mockup",
    status: "Completed",
    priority: "High",
    assignee: "Hina Shahid",
    project: "Marketing Website",
    dueDate: "2025-12-10",
    category: "Design",
  },
  {
    id: 2,
    title: "Implement user authentication",
    status: "In Progress",
    priority: "High",
    assignee: "Ahmed Khan",
    project: "E-Commerce Platform",
    dueDate: "2025-12-15",
    category: "Development",
  },
  {
    id: 3,
    title: "Write API documentation",
    status: "Todo",
    priority: "Medium",
    assignee: "Zain Malik",
    project: "CRM Integration",
    dueDate: "2025-12-20",
    category: "Documentation",
  },
  {
    id: 4,
    title: "Setup CI/CD pipeline",
    status: "In Progress",
    priority: "High",
    assignee: "Ali Raza",
    project: "Analytics Dashboard",
    dueDate: "2025-12-12",
    category: "DevOps",
  },
  {
    id: 5,
    title: "Database schema design",
    status: "Completed",
    priority: "High",
    assignee: "Zain Malik",
    project: "Mobile Banking App",
    dueDate: "2025-12-08",
    category: "Development",
  },
  {
    id: 6,
    title: "Client feedback review",
    status: "Todo",
    priority: "Low",
    assignee: "Sarah Ali",
    project: "HR Portal Redesign",
    dueDate: "2025-12-18",
    category: "Review",
  },
  {
    id: 7,
    title: "Performance optimization",
    status: "In Progress",
    priority: "Medium",
    assignee: "Ahmed Khan",
    project: "Analytics Dashboard",
    dueDate: "2025-12-22",
    category: "Development",
  },
  {
    id: 8,
    title: "Create marketing materials",
    status: "Todo",
    priority: "Medium",
    assignee: "Usman Tariq",
    project: "Marketing Website",
    dueDate: "2025-12-25",
    category: "Marketing",
  },
  {
    id: 9,
    title: "Security audit report",
    status: "Todo",
    priority: "High",
    assignee: "Ahmed Khan",
    project: "E-Commerce Platform",
    dueDate: "2025-12-28",
    category: "Security",
  },
  {
    id: 10,
    title: "Unit test coverage",
    status: "In Progress",
    priority: "Medium",
    assignee: "Ali Raza",
    project: "CRM Integration",
    dueDate: "2025-12-16",
    category: "Testing",
  },
];

// ===== CLIENTS =====
export const clients = [
  {
    id: 1,
    name: "TechCorp Ltd",
    email: "contact@techcorp.com",
    phone: "+92 21 1234567",
    status: "Active",
    projects: 3,
    totalSpent: 125000,
    joinDate: "2024-01-10",
    industry: "Technology",
  },
  {
    id: 2,
    name: "Global Systems",
    email: "info@globalsystems.com",
    phone: "+92 42 2345678",
    status: "Active",
    projects: 2,
    totalSpent: 85000,
    joinDate: "2024-03-15",
    industry: "IT Services",
  },
  {
    id: 3,
    name: "FinTech Solutions",
    email: "hello@fintech.com",
    phone: "+92 51 3456789",
    status: "Active",
    projects: 1,
    totalSpent: 65000,
    joinDate: "2024-06-20",
    industry: "Finance",
  },
  {
    id: 4,
    name: "MegaCorp Inc",
    email: "support@megacorp.com",
    phone: "+92 21 4567890",
    status: "Active",
    projects: 2,
    totalSpent: 48000,
    joinDate: "2024-02-01",
    industry: "Enterprise",
  },
  {
    id: 5,
    name: "DataDriven Co",
    email: "team@datadriven.com",
    phone: "+92 42 5678901",
    status: "Active",
    projects: 1,
    totalSpent: 32000,
    joinDate: "2024-07-10",
    industry: "Analytics",
  },
  {
    id: 6,
    name: "StartUp Hub",
    email: "admin@startuphub.com",
    phone: "+92 51 6789012",
    status: "Blocked",
    projects: 0,
    totalSpent: 8000,
    joinDate: "2024-09-01",
    industry: "Incubator",
  },
  {
    id: 7,
    name: "RetailMax",
    email: "ops@retailmax.com",
    phone: "+92 21 7890123",
    status: "Active",
    projects: 1,
    totalSpent: 22000,
    joinDate: "2024-08-15",
    industry: "Retail",
  },
  {
    id: 8,
    name: "EduTech Academy",
    email: "info@edutech.com",
    phone: "+92 42 8901234",
    status: "Active",
    projects: 1,
    totalSpent: 38000,
    joinDate: "2024-10-01",
    industry: "Education",
  },
];

export const students = [
  {
    id: 1,
    name: "Ayesha Rahman",
    email: "ayesha.rahman@studentmail.com",
    phone: "+880 1712 345678",
    status: "Active",
    courses: 3,
    totalFees: 45000,
    joinDate: "2024-01-12",
    department: "Computer Science",
  },
  {
    id: 2,
    name: "Tanvir Ahmed",
    email: "tanvir.ahmed@studentmail.com",
    phone: "+880 1812 456789",
    status: "Active",
    courses: 2,
    totalFees: 30000,
    joinDate: "2024-02-20",
    department: "Business Administration",
  },
  {
    id: 3,
    name: "Nusrat Jahan",
    email: "nusrat.jahan@studentmail.com",
    phone: "+880 1912 567890",
    status: "Inactive",
    courses: 1,
    totalFees: 15000,
    joinDate: "2024-03-05",
    department: "Mathematics",
  },
  {
    id: 4,
    name: "Sabbir Hossain",
    email: "sabbir.hossain@studentmail.com",
    phone: "+880 1612 678901",
    status: "Active",
    courses: 4,
    totalFees: 60000,
    joinDate: "2024-01-25",
    department: "Software Engineering",
  },
  {
    id: 5,
    name: "Mim Akter",
    email: "mim.akter@studentmail.com",
    phone: "+880 1512 789012",
    status: "Active",
    courses: 2,
    totalFees: 28000,
    joinDate: "2024-04-18",
    department: "Marketing",
  },
  {
    id: 6,
    name: "Rafiul Karim",
    email: "rafiul.karim@studentmail.com",
    phone: "+880 1713 890123",
    status: "Blocked",
    courses: 0,
    totalFees: 5000,
    joinDate: "2024-05-10",
    department: "Accounting",
  },
  {
    id: 7,
    name: "Farzana Islam",
    email: "farzana.islam@studentmail.com",
    phone: "+880 1813 901234",
    status: "Active",
    courses: 3,
    totalFees: 42000,
    joinDate: "2024-06-22",
    department: "Data Science",
  },
  {
    id: 8,
    name: "Imran Chowdhury",
    email: "imran.chowdhury@studentmail.com",
    phone: "+880 1913 012345",
    status: "Active",
    courses: 1,
    totalFees: 18000,
    joinDate: "2024-07-30",
    department: "Cyber Security",
  },
];

// ===== INVOICES =====
export const invoices = [
  {
    id: 1001,
    client: "TechCorp Ltd",
    amount: 15000,
    tax: 1500,
    discount: 500,
    status: "Paid",
    date: "2025-12-01",
    dueDate: "2025-12-15",
    items: 3,
  },
  {
    id: 1002,
    client: "Global Systems",
    amount: 8500,
    tax: 850,
    discount: 0,
    status: "Pending",
    date: "2025-12-05",
    dueDate: "2025-12-20",
    items: 2,
  },
  {
    id: 1003,
    client: "FinTech Solutions",
    amount: 22000,
    tax: 2200,
    discount: 1000,
    status: "Pending",
    date: "2025-12-08",
    dueDate: "2025-12-22",
    items: 5,
  },
  {
    id: 1004,
    client: "MegaCorp Inc",
    amount: 6000,
    tax: 600,
    discount: 0,
    status: "Paid",
    date: "2025-11-25",
    dueDate: "2025-12-10",
    items: 2,
  },
  {
    id: 1005,
    client: "DataDriven Co",
    amount: 12500,
    tax: 1250,
    discount: 500,
    status: "Overdue",
    date: "2025-11-15",
    dueDate: "2025-11-30",
    items: 4,
  },
  {
    id: 1006,
    client: "RetailMax",
    amount: 9800,
    tax: 980,
    discount: 0,
    status: "Cancelled",
    date: "2025-11-20",
    dueDate: "2025-12-05",
    items: 3,
  },
  {
    id: 1007,
    client: "EduTech Academy",
    amount: 18500,
    tax: 1850,
    discount: 750,
    status: "Paid",
    date: "2025-12-02",
    dueDate: "2025-12-16",
    items: 4,
  },
  {
    id: 1008,
    client: "TechCorp Ltd",
    amount: 28000,
    tax: 2800,
    discount: 1500,
    status: "Pending",
    date: "2025-12-10",
    dueDate: "2025-12-25",
    items: 6,
  },
];

// ===== MARKETING =====
export const marketingCampaigns = [
  {
    id: 1,
    name: "Winter Sale 2025",
    type: "Email",
    status: "Active",
    sent: 4500,
    opened: 2100,
    clicked: 890,
    date: "2025-12-01",
  },
  {
    id: 2,
    name: "New Year Promo",
    type: "SMS",
    status: "Scheduled",
    sent: 0,
    opened: 0,
    clicked: 0,
    date: "2025-12-28",
  },
  {
    id: 3,
    name: "Product Launch",
    type: "Push",
    status: "Completed",
    sent: 8200,
    opened: 5400,
    clicked: 2300,
    date: "2025-11-15",
  },
  {
    id: 4,
    name: "Black Friday Deal",
    type: "Email",
    status: "Completed",
    sent: 12000,
    opened: 7800,
    clicked: 4200,
    date: "2025-11-28",
  },
  {
    id: 5,
    name: "Holiday Greetings",
    type: "Email",
    status: "Draft",
    sent: 0,
    opened: 0,
    clicked: 0,
    date: "2025-12-20",
  },
  {
    id: 6,
    name: "Flash Sale Alert",
    type: "SMS",
    status: "Active",
    sent: 3200,
    opened: 0,
    clicked: 0,
    date: "2025-12-05",
  },
];

// ===== ROLES =====
export const roles = [
  {
    id: 1,
    name: "Super Admin",
    users: 2,
    permissions: "Full Access",
    description: "Complete system control",
  },
  {
    id: 2,
    name: "CRM Manager",
    users: 4,
    permissions: "CRM, Clients, Marketing",
    description: "Customer relationship management",
  },
  {
    id: 3,
    name: "HR Manager",
    users: 3,
    permissions: "HRM, Team, Attendance",
    description: "Human resource management",
  },
  {
    id: 4,
    name: "Admin",
    users: 12,
    permissions:
      "Dashboard, Projects, Tasks, Invoice Operations, Profile, Reports",
    description: "Day-to-day operations",
  },
  {
    id: 5,
    name: "Staff",
    users: 3,
    permissions: "Limited permissions",
    description: "Staff",
  },
  {
    id: 6,
    name: "Client",
    users: 5,
    permissions: "Limited permissions",
    description: "Client",
  },
  {
    id: 7,
    name: "Users",
    users: 6,
    permissions: "Projects, Tasks, Teams",
    description: "Project oversight",
  },
];

export const permissionModules = [
  "Dashboard",
  "CMS",
  "Projects",
  "Services",
  "Team",
  "Tasks",
  "Clients",
  "Invoices",
  "Marketing",
  "Roles",
  "Partnership",
  "Schools",
  "Settings",
  "Support",
  "Reports",
];

// ===== PARTNERSHIPS =====
export const partners = [
  {
    id: 1,
    name: "DigiMarketing Pro",
    type: "Referral",
    status: "Active",
    commission: 15,
    totalRevenue: 45000,
    joinDate: "2024-05-01",
  },
  {
    id: 2,
    name: "CloudHost Solutions",
    type: "Revenue Share",
    status: "Active",
    commission: 20,
    totalRevenue: 62000,
    joinDate: "2024-03-15",
  },
  {
    id: 3,
    name: "DesignStudio Co",
    type: "Referral",
    status: "Active",
    commission: 10,
    totalRevenue: 28000,
    joinDate: "2024-07-20",
  },
  {
    id: 4,
    name: "AppDev Alliance",
    type: "Revenue Share",
    status: "Inactive",
    commission: 25,
    totalRevenue: 15000,
    joinDate: "2024-09-01",
  },
  {
    id: 5,
    name: "BizConsult Group",
    type: "Referral",
    status: "Active",
    commission: 12,
    totalRevenue: 35000,
    joinDate: "2024-06-10",
  },
];

// ===== SCHOOLS =====
export const schools = [
  {
    id: 1,
    name: "ABC International School",
    students: 450,
    fees: 125000,
    status: "Active",
    location: "Lahore",
    notices: 3,
    marketingCharges: 5000,
  },
  {
    id: 2,
    name: "XYZ Grammar School",
    students: 320,
    fees: 85000,
    status: "Active",
    location: "Karachi",
    notices: 1,
    marketingCharges: 3500,
  },
  {
    id: 3,
    name: "Elite Academy",
    students: 280,
    fees: 95000,
    status: "Active",
    location: "Islamabad",
    notices: 2,
    marketingCharges: 4000,
  },
  {
    id: 4,
    name: "Star Public School",
    students: 520,
    fees: 68000,
    status: "Pending",
    location: "Rawalpindi",
    notices: 0,
    marketingCharges: 0,
  },
  {
    id: 5,
    name: "Modern Learning Center",
    students: 180,
    fees: 110000,
    status: "Active",
    location: "Faisalabad",
    notices: 4,
    marketingCharges: 6000,
  },
];

// ===== SUPPORT TICKETS =====
export const supportTickets = [
  {
    id: 1,
    subject: "Login issues after update",
    client: "TechCorp Ltd",
    priority: "High",
    status: "Open",
    assignee: "Ahmed Khan",
    date: "2025-12-10",
    category: "Technical",
  },
  {
    id: 2,
    subject: "Invoice not generating PDF",
    client: "Global Systems",
    priority: "Medium",
    status: "In Progress",
    assignee: "Ali Raza",
    date: "2025-12-09",
    category: "Bug",
  },
  {
    id: 3,
    subject: "Need API documentation",
    client: "FinTech Solutions",
    priority: "Low",
    status: "Open",
    assignee: "Zain Malik",
    date: "2025-12-08",
    category: "Documentation",
  },
  {
    id: 4,
    subject: "Payment gateway error",
    client: "MegaCorp Inc",
    priority: "High",
    status: "Resolved",
    assignee: "Ahmed Khan",
    date: "2025-12-05",
    category: "Technical",
  },
  {
    id: 5,
    subject: "Feature request: Bulk export",
    client: "DataDriven Co",
    priority: "Medium",
    status: "Open",
    assignee: "Sarah Ali",
    date: "2025-12-07",
    category: "Feature Request",
  },
  {
    id: 6,
    subject: "Dashboard loading slowly",
    client: "RetailMax",
    priority: "Medium",
    status: "In Progress",
    assignee: "Ali Raza",
    date: "2025-12-06",
    category: "Performance",
  },
];

// ===== SUCCESS STORIES =====
export const successStories = [
  {
    id: 1,
    title: "TechCorp Increased Revenue by 200%",
    client: "TechCorp Ltd",
    date: "2025-11-01",
    status: "Published",
    views: 3400,
  },
  {
    id: 2,
    title: "Global Systems Streamlined Operations",
    client: "Global Systems",
    date: "2025-10-15",
    status: "Published",
    views: 2100,
  },
  {
    id: 3,
    title: "FinTech Solutions Digital Transformation",
    client: "FinTech Solutions",
    date: "2025-09-20",
    status: "Draft",
    views: 0,
  },
  {
    id: 4,
    title: "MegaCorp Employee Satisfaction Up 45%",
    client: "MegaCorp Inc",
    date: "2025-08-10",
    status: "Published",
    views: 1800,
  },
];

// ============ CRM Mock Data ============

export const crmStats = {
  totalClients: 1248,
  activeProjects: 34,
  openTickets: 87,
  revenue: 284500,
  revenueGrowth: 12.5,
  clientsGrowth: 8.2,
  projectsGrowth: -3.1,
  ticketsGrowth: 15.7,
};

export const crmRevenueData = [
  { month: "Jan", revenue: 18500, expenses: 12400 },
  { month: "Feb", revenue: 22300, expenses: 14200 },
  { month: "Mar", revenue: 19800, expenses: 11800 },
  { month: "Apr", revenue: 27400, expenses: 16300 },
  { month: "May", revenue: 31200, expenses: 18700 },
  { month: "Jun", revenue: 28900, expenses: 15400 },
  { month: "Jul", revenue: 33100, expenses: 19200 },
  { month: "Aug", revenue: 29700, expenses: 17100 },
  { month: "Sep", revenue: 35400, expenses: 20800 },
  { month: "Oct", revenue: 32100, expenses: 18900 },
  { month: "Nov", revenue: 38200, expenses: 22100 },
  { month: "Dec", revenue: 41500, expenses: 24300 },
];

export const crmClients = [
  {
    id: 1,
    name: "Acme Corp",
    email: "contact@acme.com",
    phone: "+1 555-0101",
    company: "Acme Corporation",
    status: "active",
    value: "$45,000",
    avatar: "AC",
    joinDate: "2024-01-15",
  },
  {
    id: 2,
    name: "GlobalTech Inc",
    email: "info@globaltech.io",
    phone: "+1 555-0102",
    company: "GlobalTech",
    status: "active",
    value: "$72,000",
    avatar: "GT",
    joinDate: "2024-02-20",
  },
  {
    id: 3,
    name: "Sunrise Media",
    email: "hello@sunrise.co",
    phone: "+1 555-0103",
    company: "Sunrise Media Group",
    status: "inactive",
    value: "$18,500",
    avatar: "SM",
    joinDate: "2023-11-08",
  },
  {
    id: 4,
    name: "Blue Ocean Ltd",
    email: "sales@blueocean.com",
    phone: "+1 555-0104",
    company: "Blue Ocean",
    status: "active",
    value: "$93,200",
    avatar: "BO",
    joinDate: "2024-03-01",
  },
  {
    id: 5,
    name: "Peak Solutions",
    email: "admin@peak.dev",
    phone: "+1 555-0105",
    company: "Peak Solutions LLC",
    status: "active",
    value: "$56,700",
    avatar: "PS",
    joinDate: "2024-01-22",
  },
  {
    id: 6,
    name: "NovaTech",
    email: "team@novatech.com",
    phone: "+1 555-0106",
    company: "NovaTech Systems",
    status: "pending",
    value: "$31,400",
    avatar: "NT",
    joinDate: "2024-04-10",
  },
  {
    id: 7,
    name: "CloudNine SaaS",
    email: "support@cloudnine.io",
    phone: "+1 555-0107",
    company: "CloudNine",
    status: "active",
    value: "$125,000",
    avatar: "CN",
    joinDate: "2023-09-15",
  },
  {
    id: 8,
    name: "DataFlow Analytics",
    email: "info@dataflow.ai",
    phone: "+1 555-0108",
    company: "DataFlow",
    status: "active",
    value: "$67,800",
    avatar: "DF",
    joinDate: "2024-02-14",
  },
];

export const crmLeads = [
  {
    id: 1,
    name: "Sarah Mitchell",
    email: "sarah@techstart.io",
    company: "TechStart",
    stage: "qualified",
    value: "$25,000",
    source: "Website",
    probability: 75,
  },
  {
    id: 2,
    name: "James Cooper",
    email: "james@fincore.com",
    company: "FinCore",
    stage: "proposal",
    value: "$48,000",
    source: "Referral",
    probability: 60,
  },
  {
    id: 3,
    name: "Emily Watson",
    email: "emily@designhub.co",
    company: "DesignHub",
    stage: "negotiation",
    value: "$15,800",
    source: "LinkedIn",
    probability: 85,
  },
  {
    id: 4,
    name: "Michael Chen",
    email: "mchen@rapidgrow.com",
    company: "RapidGrow",
    stage: "new",
    value: "$33,000",
    source: "Cold Call",
    probability: 20,
  },
  {
    id: 5,
    name: "Lisa Park",
    email: "lisa@greenleaf.org",
    company: "GreenLeaf",
    stage: "qualified",
    value: "$62,000",
    source: "Conference",
    probability: 55,
  },
  {
    id: 6,
    name: "David Brown",
    email: "dbrown@nextstep.io",
    company: "NextStep",
    stage: "proposal",
    value: "$41,500",
    source: "Website",
    probability: 70,
  },
  {
    id: 7,
    name: "Anna Torres",
    email: "anna@brightpath.com",
    company: "BrightPath",
    stage: "new",
    value: "$19,200",
    source: "Email Campaign",
    probability: 15,
  },
  {
    id: 8,
    name: "Robert Kim",
    email: "rkim@skyline.dev",
    company: "Skyline Dev",
    stage: "negotiation",
    value: "$87,000",
    source: "Referral",
    probability: 90,
  },
];

export const crmPipelineData = [
  { stage: "New", count: 24, value: 156000 },
  { stage: "Qualified", count: 18, value: 312000 },
  { stage: "Proposal", count: 12, value: 487000 },
  { stage: "Negotiation", count: 8, value: 394000 },
  { stage: "Closed Won", count: 15, value: 628000 },
];

export const crmTickets = [
  {
    id: "TKT-001",
    subject: "Login issue on mobile",
    client: "Acme Corp",
    priority: "high",
    status: "open",
    assignee: "John D.",
    created: "2024-12-01",
  },
  {
    id: "TKT-002",
    subject: "Payment gateway error",
    client: "GlobalTech Inc",
    priority: "critical",
    status: "in_progress",
    assignee: "Sarah K.",
    created: "2024-12-02",
  },
  {
    id: "TKT-003",
    subject: "Feature request: dark mode",
    client: "Blue Ocean Ltd",
    priority: "low",
    status: "open",
    assignee: "Mike R.",
    created: "2024-12-03",
  },
  {
    id: "TKT-004",
    subject: "Data export not working",
    client: "Peak Solutions",
    priority: "medium",
    status: "resolved",
    assignee: "Emily W.",
    created: "2024-11-28",
  },
  {
    id: "TKT-005",
    subject: "API rate limiting",
    client: "CloudNine SaaS",
    priority: "high",
    status: "in_progress",
    assignee: "John D.",
    created: "2024-12-04",
  },
  {
    id: "TKT-006",
    subject: "Dashboard loading slow",
    client: "NovaTech",
    priority: "medium",
    status: "open",
    assignee: "Sarah K.",
    created: "2024-12-05",
  },
  {
    id: "TKT-007",
    subject: "Email notifications delay",
    client: "DataFlow Analytics",
    priority: "low",
    status: "resolved",
    assignee: "Mike R.",
    created: "2024-11-25",
  },
  {
    id: "TKT-008",
    subject: "SSO integration issue",
    client: "Sunrise Media",
    priority: "critical",
    status: "open",
    assignee: "Emily W.",
    created: "2024-12-06",
  },
];

export const crmProjects = [
  {
    id: 1,
    name: "Website Redesign",
    client: "Acme Corp",
    status: "in_progress",
    progress: 65,
    budget: "$45,000",
    deadline: "2025-03-15",
    team: 5,
  },
  {
    id: 2,
    name: "Mobile App v2.0",
    client: "GlobalTech Inc",
    status: "in_progress",
    progress: 40,
    budget: "$82,000",
    deadline: "2025-05-01",
    team: 8,
  },
  {
    id: 3,
    name: "CRM Integration",
    client: "Blue Ocean Ltd",
    status: "planning",
    progress: 10,
    budget: "$28,000",
    deadline: "2025-04-20",
    team: 3,
  },
  {
    id: 4,
    name: "Analytics Dashboard",
    client: "CloudNine SaaS",
    status: "completed",
    progress: 100,
    budget: "$35,000",
    deadline: "2024-12-01",
    team: 4,
  },
  {
    id: 5,
    name: "E-commerce Platform",
    client: "Peak Solutions",
    status: "in_progress",
    progress: 78,
    budget: "$120,000",
    deadline: "2025-02-28",
    team: 10,
  },
  {
    id: 6,
    name: "API Development",
    client: "DataFlow Analytics",
    status: "on_hold",
    progress: 30,
    budget: "$52,000",
    deadline: "2025-06-15",
    team: 6,
  },
];

export const crmInvoices = [
  {
    id: "INV-001",
    client: "Acme Corp",
    amount: "$12,500",
    status: "paid",
    date: "2024-12-01",
    dueDate: "2024-12-15",
  },
  {
    id: "INV-002",
    client: "GlobalTech Inc",
    amount: "$28,400",
    status: "pending",
    date: "2024-12-05",
    dueDate: "2024-12-20",
  },
  {
    id: "INV-003",
    client: "Blue Ocean Ltd",
    amount: "$8,750",
    status: "overdue",
    date: "2024-11-15",
    dueDate: "2024-11-30",
  },
  {
    id: "INV-004",
    client: "CloudNine SaaS",
    amount: "$35,000",
    status: "paid",
    date: "2024-11-28",
    dueDate: "2024-12-12",
  },
  {
    id: "INV-005",
    client: "Peak Solutions",
    amount: "$19,200",
    status: "pending",
    date: "2024-12-08",
    dueDate: "2024-12-22",
  },
  {
    id: "INV-006",
    client: "NovaTech",
    amount: "$6,300",
    status: "draft",
    date: "2024-12-10",
    dueDate: "2024-12-24",
  },
  {
    id: "INV-007",
    client: "DataFlow Analytics",
    amount: "$42,100",
    status: "paid",
    date: "2024-11-20",
    dueDate: "2024-12-04",
  },
  {
    id: "INV-008",
    client: "Sunrise Media",
    amount: "$15,800",
    status: "overdue",
    date: "2024-11-10",
    dueDate: "2024-11-24",
  },
];

export const crmTasks = [
  {
    id: 1,
    title: "Prepare Q4 report",
    project: "Analytics Dashboard",
    assignee: "John D.",
    priority: "high",
    status: "in_progress",
    dueDate: "2024-12-15",
  },
  {
    id: 2,
    title: "Client onboarding call",
    project: "CRM Integration",
    assignee: "Sarah K.",
    priority: "medium",
    status: "pending",
    dueDate: "2024-12-12",
  },
  {
    id: 3,
    title: "UI mockups review",
    project: "Website Redesign",
    assignee: "Mike R.",
    priority: "high",
    status: "completed",
    dueDate: "2024-12-10",
  },
  {
    id: 4,
    title: "Backend API testing",
    project: "Mobile App v2.0",
    assignee: "Emily W.",
    priority: "critical",
    status: "in_progress",
    dueDate: "2024-12-13",
  },
  {
    id: 5,
    title: "Deploy staging env",
    project: "E-commerce Platform",
    assignee: "John D.",
    priority: "medium",
    status: "pending",
    dueDate: "2024-12-16",
  },
  {
    id: 6,
    title: "Database migration",
    project: "API Development",
    assignee: "Sarah K.",
    priority: "high",
    status: "pending",
    dueDate: "2024-12-18",
  },
  {
    id: 7,
    title: "Security audit",
    project: "Mobile App v2.0",
    assignee: "Mike R.",
    priority: "critical",
    status: "in_progress",
    dueDate: "2024-12-14",
  },
  {
    id: 8,
    title: "Write documentation",
    project: "CRM Integration",
    assignee: "Emily W.",
    priority: "low",
    status: "pending",
    dueDate: "2024-12-20",
  },
];

export const crmTeam = [
  {
    id: 1,
    name: "John Doe",
    role: "Project Manager",
    email: "john@jevxo.com",
    department: "Management",
    status: "online",
    projects: 4,
    avatar: "JD",
  },
  {
    id: 2,
    name: "Sarah Kim",
    role: "Senior Developer",
    email: "sarah@jevxo.com",
    department: "Engineering",
    status: "online",
    projects: 3,
    avatar: "SK",
  },
  {
    id: 3,
    name: "Mike Roberts",
    role: "UI/UX Designer",
    email: "mike@jevxo.com",
    department: "Design",
    status: "away",
    projects: 2,
    avatar: "MR",
  },
  {
    id: 4,
    name: "Emily Wang",
    role: "Backend Developer",
    email: "emily@jevxo.com",
    department: "Engineering",
    status: "online",
    projects: 5,
    avatar: "EW",
  },
  {
    id: 5,
    name: "Alex Johnson",
    role: "QA Engineer",
    email: "alex@jevxo.com",
    department: "QA",
    status: "offline",
    projects: 3,
    avatar: "AJ",
  },
  {
    id: 6,
    name: "Diana Cruz",
    role: "DevOps Engineer",
    email: "diana@jevxo.com",
    department: "Engineering",
    status: "online",
    projects: 6,
    avatar: "DC",
  },
];

export const crmMeetings = [
  {
    id: 1,
    title: "Sprint Planning",
    date: "2024-12-12",
    time: "10:00 AM",
    duration: "1h",
    attendees: 8,
    type: "internal",
    status: "upcoming",
  },
  {
    id: 2,
    title: "Client Review - Acme",
    date: "2024-12-13",
    time: "2:00 PM",
    duration: "45m",
    attendees: 4,
    type: "client",
    status: "upcoming",
  },
  {
    id: 3,
    title: "Design Workshop",
    date: "2024-12-11",
    time: "11:00 AM",
    duration: "2h",
    attendees: 6,
    type: "internal",
    status: "completed",
  },
  {
    id: 4,
    title: "Quarterly Review",
    date: "2024-12-14",
    time: "9:00 AM",
    duration: "1.5h",
    attendees: 12,
    type: "internal",
    status: "upcoming",
  },
  {
    id: 5,
    title: "Sales Demo - NovaTech",
    date: "2024-12-15",
    time: "3:00 PM",
    duration: "30m",
    attendees: 3,
    type: "client",
    status: "upcoming",
  },
  {
    id: 6,
    title: "Tech Sync",
    date: "2024-12-10",
    time: "4:00 PM",
    duration: "30m",
    attendees: 5,
    type: "internal",
    status: "completed",
  },
];

export const crmReports = {
  conversionRate: 32.5,
  avgDealSize: 42800,
  salesCycle: 28,
  customerSatisfaction: 4.6,
  sourceData: [
    { name: "Website", value: 35 },
    { name: "Referral", value: 25 },
    { name: "LinkedIn", value: 18 },
    { name: "Cold Call", value: 12 },
    { name: "Email", value: 10 },
  ],
};

// ============ HRM Mock Data ============

export const hrmStats = {
  totalEmployees: 156,
  departments: 8,
  openPositions: 12,
  avgAttendance: 94.2,
  employeesGrowth: 5.3,
  departmentsGrowth: 0,
  positionsGrowth: 33.3,
  attendanceGrowth: -1.2,
};

export const hrmEmployees = [
  {
    id: 1,
    name: "John Doe",
    email: "john@jevxo.com",
    department: "Engineering",
    position: "Senior Developer",
    status: "active",
    salary: "$95,000",
    joinDate: "2022-03-15",
    avatar: "JD",
  },
  {
    id: 2,
    name: "Sarah Kim",
    email: "sarah@jevxo.com",
    department: "Engineering",
    position: "Tech Lead",
    status: "active",
    salary: "$120,000",
    joinDate: "2021-06-20",
    avatar: "SK",
  },
  {
    id: 3,
    name: "Mike Roberts",
    email: "mike@jevxo.com",
    department: "Design",
    position: "UI/UX Lead",
    status: "active",
    salary: "$88,000",
    joinDate: "2022-09-01",
    avatar: "MR",
  },
  {
    id: 4,
    name: "Emily Wang",
    email: "emily@jevxo.com",
    department: "Engineering",
    position: "Backend Developer",
    status: "active",
    salary: "$92,000",
    joinDate: "2023-01-10",
    avatar: "EW",
  },
  {
    id: 5,
    name: "Alex Johnson",
    email: "alex@jevxo.com",
    department: "QA",
    position: "QA Lead",
    status: "on_leave",
    salary: "$78,000",
    joinDate: "2022-11-15",
    avatar: "AJ",
  },
  {
    id: 6,
    name: "Diana Cruz",
    email: "diana@jevxo.com",
    department: "DevOps",
    position: "DevOps Engineer",
    status: "active",
    salary: "$105,000",
    joinDate: "2021-08-05",
    avatar: "DC",
  },
  {
    id: 7,
    name: "Tom Harris",
    email: "tom@jevxo.com",
    department: "Marketing",
    position: "Marketing Manager",
    status: "active",
    salary: "$82,000",
    joinDate: "2023-04-18",
    avatar: "TH",
  },
  {
    id: 8,
    name: "Rachel Green",
    email: "rachel@jevxo.com",
    department: "HR",
    position: "HR Specialist",
    status: "active",
    salary: "$68,000",
    joinDate: "2023-07-22",
    avatar: "RG",
  },
  {
    id: 9,
    name: "Chris Lee",
    email: "chris@jevxo.com",
    department: "Sales",
    position: "Sales Director",
    status: "active",
    salary: "$110,000",
    joinDate: "2021-02-14",
    avatar: "CL",
  },
  {
    id: 10,
    name: "Nina Patel",
    email: "nina@jevxo.com",
    department: "Finance",
    position: "Financial Analyst",
    status: "active",
    salary: "$75,000",
    joinDate: "2023-10-01",
    avatar: "NP",
  },
];

export const hrmPayroll = [
  {
    id: 1,
    employee: "John Doe",
    department: "Engineering",
    baseSalary: "$7,917",
    bonus: "$500",
    deductions: "$1,850",
    netPay: "$6,567",
    status: "processed",
    month: "Dec 2024",
  },
  {
    id: 2,
    employee: "Sarah Kim",
    department: "Engineering",
    baseSalary: "$10,000",
    bonus: "$800",
    deductions: "$2,400",
    netPay: "$8,400",
    status: "processed",
    month: "Dec 2024",
  },
  {
    id: 3,
    employee: "Mike Roberts",
    department: "Design",
    baseSalary: "$7,333",
    bonus: "$300",
    deductions: "$1,680",
    netPay: "$5,953",
    status: "pending",
    month: "Dec 2024",
  },
  {
    id: 4,
    employee: "Emily Wang",
    department: "Engineering",
    baseSalary: "$7,667",
    bonus: "$450",
    deductions: "$1,790",
    netPay: "$6,327",
    status: "processed",
    month: "Dec 2024",
  },
  {
    id: 5,
    employee: "Alex Johnson",
    department: "QA",
    baseSalary: "$6,500",
    bonus: "$200",
    deductions: "$1,470",
    netPay: "$5,230",
    status: "pending",
    month: "Dec 2024",
  },
  {
    id: 6,
    employee: "Diana Cruz",
    department: "DevOps",
    baseSalary: "$8,750",
    bonus: "$600",
    deductions: "$2,060",
    netPay: "$7,290",
    status: "processed",
    month: "Dec 2024",
  },
];

export const hrmPayrollSummary = [
  { month: "Jul", totalPayout: 142000, employees: 148 },
  { month: "Aug", totalPayout: 145000, employees: 150 },
  { month: "Sep", totalPayout: 148000, employees: 152 },
  { month: "Oct", totalPayout: 150000, employees: 153 },
  { month: "Nov", totalPayout: 152000, employees: 155 },
  { month: "Dec", totalPayout: 155000, employees: 156 },
];

export const hrmLeaveRequests = [
  {
    id: 1,
    employee: "John Doe",
    type: "Annual Leave",
    from: "2024-12-20",
    to: "2024-12-27",
    days: 5,
    status: "approved",
    reason: "Family vacation",
  },
  {
    id: 2,
    employee: "Sarah Kim",
    type: "Sick Leave",
    from: "2024-12-10",
    to: "2024-12-11",
    days: 2,
    status: "approved",
    reason: "Medical appointment",
  },
  {
    id: 3,
    employee: "Mike Roberts",
    type: "Annual Leave",
    from: "2025-01-02",
    to: "2025-01-10",
    days: 7,
    status: "pending",
    reason: "Personal trip",
  },
  {
    id: 4,
    employee: "Emily Wang",
    type: "Work From Home",
    from: "2024-12-12",
    to: "2024-12-13",
    days: 2,
    status: "approved",
    reason: "Home repairs",
  },
  {
    id: 5,
    employee: "Alex Johnson",
    type: "Sick Leave",
    from: "2024-12-08",
    to: "2024-12-12",
    days: 5,
    status: "approved",
    reason: "Recovery",
  },
  {
    id: 6,
    employee: "Diana Cruz",
    type: "Annual Leave",
    from: "2024-12-23",
    to: "2024-12-31",
    days: 7,
    status: "pending",
    reason: "Holiday break",
  },
  {
    id: 7,
    employee: "Tom Harris",
    type: "Compassionate",
    from: "2024-12-15",
    to: "2024-12-17",
    days: 3,
    status: "approved",
    reason: "Family emergency",
  },
];

export const hrmAttendance = [
  {
    id: 1,
    employee: "John Doe",
    date: "2024-12-11",
    checkIn: "08:55",
    checkOut: "17:30",
    hours: "8h 35m",
    status: "present",
    overtime: "35m",
  },
  {
    id: 2,
    employee: "Sarah Kim",
    date: "2024-12-11",
    checkIn: "09:02",
    checkOut: "18:15",
    hours: "9h 13m",
    status: "present",
    overtime: "1h 13m",
  },
  {
    id: 3,
    employee: "Mike Roberts",
    date: "2024-12-11",
    checkIn: "09:30",
    checkOut: "17:00",
    hours: "7h 30m",
    status: "late",
    overtime: "0m",
  },
  {
    id: 4,
    employee: "Emily Wang",
    date: "2024-12-11",
    checkIn: "08:45",
    checkOut: "17:45",
    hours: "9h 00m",
    status: "present",
    overtime: "1h",
  },
  {
    id: 5,
    employee: "Alex Johnson",
    date: "2024-12-11",
    checkIn: "-",
    checkOut: "-",
    hours: "-",
    status: "on_leave",
    overtime: "-",
  },
  {
    id: 6,
    employee: "Diana Cruz",
    date: "2024-12-11",
    checkIn: "08:30",
    checkOut: "18:00",
    hours: "9h 30m",
    status: "present",
    overtime: "1h 30m",
  },
  {
    id: 7,
    employee: "Tom Harris",
    date: "2024-12-11",
    checkIn: "09:10",
    checkOut: "17:15",
    hours: "8h 05m",
    status: "present",
    overtime: "5m",
  },
  {
    id: 8,
    employee: "Rachel Green",
    date: "2024-12-11",
    checkIn: "-",
    checkOut: "-",
    hours: "-",
    status: "absent",
    overtime: "-",
  },
];

export const hrmPerformanceReviews = [
  {
    id: 1,
    employee: "John Doe",
    department: "Engineering",
    rating: 4.5,
    reviewDate: "2024-11-15",
    reviewer: "Sarah Kim",
    status: "completed",
    strengths: "Technical expertise, leadership",
    areas: "Communication",
  },
  {
    id: 2,
    employee: "Sarah Kim",
    department: "Engineering",
    rating: 4.8,
    reviewDate: "2024-11-15",
    reviewer: "CTO",
    status: "completed",
    strengths: "Strategic thinking, mentoring",
    areas: "Delegation",
  },
  {
    id: 3,
    employee: "Mike Roberts",
    department: "Design",
    rating: 4.2,
    reviewDate: "2024-11-20",
    reviewer: "Design Director",
    status: "completed",
    strengths: "Creativity, attention to detail",
    areas: "Time management",
  },
  {
    id: 4,
    employee: "Emily Wang",
    department: "Engineering",
    rating: 4.0,
    reviewDate: "2024-12-01",
    reviewer: "Sarah Kim",
    status: "pending",
    strengths: "Problem solving, efficiency",
    areas: "Documentation",
  },
  {
    id: 5,
    employee: "Alex Johnson",
    department: "QA",
    rating: 3.8,
    reviewDate: "2024-12-05",
    reviewer: "QA Director",
    status: "pending",
    strengths: "Thoroughness, automation",
    areas: "Proactiveness",
  },
  {
    id: 6,
    employee: "Diana Cruz",
    department: "DevOps",
    rating: 4.7,
    reviewDate: "2024-11-18",
    reviewer: "CTO",
    status: "completed",
    strengths: "Infrastructure, reliability",
    areas: "Knowledge sharing",
  },
];

export const hrmRecruitment = [
  {
    id: 1,
    position: "Senior React Developer",
    department: "Engineering",
    applicants: 45,
    shortlisted: 8,
    status: "interviewing",
    posted: "2024-11-20",
    type: "Full-time",
  },
  {
    id: 2,
    position: "UI/UX Designer",
    department: "Design",
    applicants: 32,
    shortlisted: 5,
    status: "open",
    posted: "2024-12-01",
    type: "Full-time",
  },
  {
    id: 3,
    position: "DevOps Engineer",
    department: "DevOps",
    applicants: 28,
    shortlisted: 6,
    status: "interviewing",
    posted: "2024-11-15",
    type: "Full-time",
  },
  {
    id: 4,
    position: "Marketing Intern",
    department: "Marketing",
    applicants: 67,
    shortlisted: 10,
    status: "screening",
    posted: "2024-12-05",
    type: "Internship",
  },
  {
    id: 5,
    position: "Financial Analyst",
    department: "Finance",
    applicants: 22,
    shortlisted: 4,
    status: "offer_sent",
    posted: "2024-11-01",
    type: "Full-time",
  },
  {
    id: 6,
    position: "Sales Representative",
    department: "Sales",
    applicants: 38,
    shortlisted: 7,
    status: "open",
    posted: "2024-12-08",
    type: "Full-time",
  },
];

export const hrmDocuments = [
  {
    id: 1,
    name: "Employee Handbook 2024",
    type: "Policy",
    department: "HR",
    uploadedBy: "Rachel Green",
    date: "2024-01-05",
    size: "2.4 MB",
  },
  {
    id: 2,
    name: "Q4 Performance Report",
    type: "Report",
    department: "Management",
    uploadedBy: "Sarah Kim",
    date: "2024-12-01",
    size: "1.8 MB",
  },
  {
    id: 3,
    name: "Leave Policy Update",
    type: "Policy",
    department: "HR",
    uploadedBy: "Rachel Green",
    date: "2024-11-20",
    size: "540 KB",
  },
  {
    id: 4,
    name: "IT Security Guidelines",
    type: "Guidelines",
    department: "IT",
    uploadedBy: "Diana Cruz",
    date: "2024-10-15",
    size: "1.2 MB",
  },
  {
    id: 5,
    name: "Onboarding Checklist",
    type: "Template",
    department: "HR",
    uploadedBy: "Rachel Green",
    date: "2024-09-01",
    size: "320 KB",
  },
  {
    id: 6,
    name: "Salary Structure 2025",
    type: "Policy",
    department: "Finance",
    uploadedBy: "Nina Patel",
    date: "2024-12-08",
    size: "890 KB",
  },
];

export const hrmNotices = [
  {
    id: 1,
    title: "Holiday Schedule 2025",
    category: "General",
    date: "2024-12-10",
    priority: "medium",
    content: "Please find the updated holiday schedule for 2025 attached.",
  },
  {
    id: 2,
    title: "Office Renovation Notice",
    category: "Facility",
    date: "2024-12-08",
    priority: "high",
    content: "The 3rd floor will undergo renovation starting Jan 5th.",
  },
  {
    id: 3,
    title: "Annual Party Invitation",
    category: "Events",
    date: "2024-12-05",
    priority: "low",
    content: "You're invited to the annual year-end celebration on Dec 20th.",
  },
  {
    id: 4,
    title: "New Health Insurance Plan",
    category: "Benefits",
    date: "2024-12-03",
    priority: "high",
    content:
      "Updated health insurance options are now available for enrollment.",
  },
  {
    id: 5,
    title: "Training: AWS Certification",
    category: "Training",
    date: "2024-12-01",
    priority: "medium",
    content: "Free AWS certification training available for engineering team.",
  },
  {
    id: 6,
    title: "Parking Policy Update",
    category: "Facility",
    date: "2024-11-28",
    priority: "low",
    content: "New parking allocation rules effective from January 2025.",
  },
];

export const hrmDepartmentData = [
  { name: "Engineering", count: 42 },
  { name: "Design", count: 15 },
  { name: "Marketing", count: 18 },
  { name: "Sales", count: 22 },
  { name: "HR", count: 8 },
  { name: "Finance", count: 12 },
  { name: "DevOps", count: 10 },
  { name: "QA", count: 14 },
];

export const hrmAttendanceTrend = [
  { month: "Jul", present: 92, late: 5, absent: 3 },
  { month: "Aug", present: 94, late: 4, absent: 2 },
  { month: "Sep", present: 91, late: 6, absent: 3 },
  { month: "Oct", present: 95, late: 3, absent: 2 },
  { month: "Nov", present: 93, late: 4, absent: 3 },
  { month: "Dec", present: 94, late: 4, absent: 2 },
];

// ============ CRM Shop Mock Data ============

export const crmShopProducts = [
  {
    id: 1,
    name: "Enterprise CRM License",
    category: "Software",
    price: "$2,400/yr",
    stock: 999,
    sold: 312,
    status: "active",
    image: "CRM",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Priority Support Plan",
    category: "Service",
    price: "$199/mo",
    stock: 999,
    sold: 187,
    status: "active",
    image: "SUP",
    rating: 4.6,
  },
  {
    id: 3,
    name: "API Access Pack",
    category: "Add-on",
    price: "$99/mo",
    stock: 999,
    sold: 245,
    status: "active",
    image: "API",
    rating: 4.5,
  },
  {
    id: 4,
    name: "Additional Storage (500GB)",
    category: "Add-on",
    price: "$49/mo",
    stock: 999,
    sold: 423,
    status: "active",
    image: "STR",
    rating: 4.3,
  },
  {
    id: 5,
    name: "Custom Integration Setup",
    category: "Service",
    price: "$5,000",
    stock: 50,
    sold: 28,
    status: "active",
    image: "INT",
    rating: 4.9,
  },
  {
    id: 6,
    name: "Training Sessions (10 pack)",
    category: "Service",
    price: "$1,500",
    stock: 100,
    sold: 64,
    status: "active",
    image: "TRN",
    rating: 4.7,
  },
  {
    id: 7,
    name: "White-Label Branding Kit",
    category: "Add-on",
    price: "$799",
    stock: 200,
    sold: 89,
    status: "active",
    image: "BRD",
    rating: 4.4,
  },
  {
    id: 8,
    name: "Data Migration Service",
    category: "Service",
    price: "$3,500",
    stock: 30,
    sold: 15,
    status: "low_stock",
    image: "MIG",
    rating: 4.8,
  },
];

export const crmShopOrders = [
  {
    id: "SO-001",
    customer: "Acme Corp",
    product: "Enterprise CRM License",
    amount: "$2,400",
    status: "completed",
    date: "2024-12-10",
  },
  {
    id: "SO-002",
    customer: "GlobalTech Inc",
    product: "Priority Support Plan",
    amount: "$199",
    status: "active",
    date: "2024-12-09",
  },
  {
    id: "SO-003",
    customer: "Blue Ocean Ltd",
    product: "Custom Integration Setup",
    amount: "$5,000",
    status: "in_progress",
    date: "2024-12-08",
  },
  {
    id: "SO-004",
    customer: "CloudNine SaaS",
    product: "API Access Pack",
    amount: "$99",
    status: "active",
    date: "2024-12-07",
  },
  {
    id: "SO-005",
    customer: "Peak Solutions",
    product: "Training Sessions (10 pack)",
    amount: "$1,500",
    status: "completed",
    date: "2024-12-05",
  },
  {
    id: "SO-006",
    customer: "NovaTech",
    product: "Additional Storage (500GB)",
    amount: "$49",
    status: "active",
    date: "2024-12-04",
  },
];

export const crmShopStats = {
  totalRevenue: 185400,
  totalOrders: 1263,
  activeSubscriptions: 524,
  avgOrderValue: 147,
};

// ============ CRM Follow-ups Mock Data ============

export const crmFollowUps = [
  {
    id: 1,
    contact: "Sarah Mitchell",
    company: "TechStart",
    type: "call",
    subject: "Discuss proposal terms",
    dueDate: "2024-12-12",
    status: "pending",
    priority: "high",
    assignee: "John D.",
    notes: "Follow up on Q1 proposal pricing",
  },
  {
    id: 2,
    contact: "James Cooper",
    company: "FinCore",
    type: "email",
    subject: "Send revised quote",
    dueDate: "2024-12-13",
    status: "pending",
    priority: "medium",
    assignee: "Sarah K.",
    notes: "Include volume discount options",
  },
  {
    id: 3,
    contact: "Emily Watson",
    company: "DesignHub",
    type: "meeting",
    subject: "Contract negotiation",
    dueDate: "2024-12-14",
    status: "scheduled",
    priority: "high",
    assignee: "John D.",
    notes: "Final negotiation before signing",
  },
  {
    id: 4,
    contact: "Michael Chen",
    company: "RapidGrow",
    type: "call",
    subject: "Initial discovery call",
    dueDate: "2024-12-11",
    status: "completed",
    priority: "low",
    assignee: "Mike R.",
    notes: "Interested in CRM module only",
  },
  {
    id: 5,
    contact: "Lisa Park",
    company: "GreenLeaf",
    type: "email",
    subject: "Product demo follow-up",
    dueDate: "2024-12-15",
    status: "pending",
    priority: "medium",
    assignee: "Emily W.",
    notes: "Send demo recording and pricing sheet",
  },
  {
    id: 6,
    contact: "David Brown",
    company: "NextStep",
    type: "meeting",
    subject: "Technical requirements review",
    dueDate: "2024-12-16",
    status: "scheduled",
    priority: "high",
    assignee: "Sarah K.",
    notes: "Bring solutions architect",
  },
  {
    id: 7,
    contact: "Anna Torres",
    company: "BrightPath",
    type: "call",
    subject: "Check-in after trial",
    dueDate: "2024-12-10",
    status: "overdue",
    priority: "medium",
    assignee: "John D.",
    notes: "Trial ending in 3 days",
  },
  {
    id: 8,
    contact: "Robert Kim",
    company: "Skyline Dev",
    type: "email",
    subject: "Send contract for review",
    dueDate: "2024-12-17",
    status: "pending",
    priority: "high",
    assignee: "Emily W.",
    notes: "Legal review completed",
  },
];

// ============ CRM Notes Mock Data ============

export const crmNotes = [
  {
    id: 1,
    title: "Acme Corp - Q1 Planning",
    client: "Acme Corp",
    author: "John D.",
    date: "2024-12-10",
    category: "strategy",
    content:
      "Client wants to expand CRM usage to 3 more departments. Budget approved for Q1. Need to prepare migration plan and training schedule.",
    pinned: true,
  },
  {
    id: 2,
    title: "GlobalTech Integration Issues",
    client: "GlobalTech Inc",
    author: "Sarah K.",
    date: "2024-12-09",
    category: "technical",
    content:
      "API rate limits causing sync delays. Need to implement batch processing. Client aware and expecting fix by Dec 20.",
    pinned: false,
  },
  {
    id: 3,
    title: "Blue Ocean - Upsell Opportunity",
    client: "Blue Ocean Ltd",
    author: "Emily W.",
    date: "2024-12-08",
    category: "sales",
    content:
      "Client expressed interest in analytics dashboard addon. Current contract up for renewal in Feb. Good timing for upsell.",
    pinned: true,
  },
  {
    id: 4,
    title: "CloudNine Feedback Session",
    client: "CloudNine SaaS",
    author: "Mike R.",
    date: "2024-12-07",
    category: "feedback",
    content:
      "Very positive feedback on new UI redesign. Requested dark mode and keyboard shortcuts. Will add to roadmap.",
    pinned: false,
  },
  {
    id: 5,
    title: "Peak Solutions - Onboarding Notes",
    client: "Peak Solutions",
    author: "John D.",
    date: "2024-12-06",
    category: "onboarding",
    content:
      "Onboarding going smoothly. 80% of team has completed training. Remaining staff scheduled for next week.",
    pinned: false,
  },
  {
    id: 6,
    title: "NovaTech Contract Discussion",
    client: "NovaTech",
    author: "Sarah K.",
    date: "2024-12-05",
    category: "legal",
    content:
      "Legal team reviewing MSA. Minor concerns about data residency clause. Expected to resolve by Dec 15.",
    pinned: false,
  },
  {
    id: 7,
    title: "DataFlow - Custom Report Requirements",
    client: "DataFlow Analytics",
    author: "Emily W.",
    date: "2024-12-04",
    category: "requirements",
    content:
      "Client needs 5 custom report templates: Sales pipeline, Revenue forecast, Team performance, Client retention, Monthly summary.",
    pinned: true,
  },
  {
    id: 8,
    title: "Sunrise Media - Account Risk",
    client: "Sunrise Media",
    author: "John D.",
    date: "2024-12-03",
    category: "risk",
    content:
      "Client has been unresponsive for 2 weeks. Last payment overdue. Schedule urgent call with account manager.",
    pinned: true,
  },
];

// ============ CRM Conversion Tracking Mock Data ============

export const crmConversions = [
  {
    id: 1,
    lead: "Sarah Mitchell",
    company: "TechStart",
    source: "Website",
    startDate: "2024-09-15",
    convertDate: "2024-11-20",
    stage: "converted",
    dealValue: "$25,000",
    daysToConvert: 66,
    assignee: "John D.",
  },
  {
    id: 2,
    lead: "James Cooper",
    company: "FinCore",
    source: "Referral",
    startDate: "2024-10-01",
    convertDate: "-",
    stage: "proposal",
    dealValue: "$48,000",
    daysToConvert: null,
    assignee: "Sarah K.",
  },
  {
    id: 3,
    lead: "Emily Watson",
    company: "DesignHub",
    source: "LinkedIn",
    startDate: "2024-08-20",
    convertDate: "2024-11-30",
    stage: "converted",
    dealValue: "$15,800",
    daysToConvert: 102,
    assignee: "Emily W.",
  },
  {
    id: 4,
    lead: "Michael Chen",
    company: "RapidGrow",
    source: "Cold Call",
    startDate: "2024-11-01",
    convertDate: "-",
    stage: "new",
    dealValue: "$33,000",
    daysToConvert: null,
    assignee: "Mike R.",
  },
  {
    id: 5,
    lead: "Lisa Park",
    company: "GreenLeaf",
    source: "Conference",
    startDate: "2024-10-15",
    convertDate: "-",
    stage: "qualified",
    dealValue: "$62,000",
    daysToConvert: null,
    assignee: "John D.",
  },
  {
    id: 6,
    lead: "David Brown",
    company: "NextStep",
    source: "Website",
    startDate: "2024-09-01",
    convertDate: "2024-12-05",
    stage: "converted",
    dealValue: "$41,500",
    daysToConvert: 95,
    assignee: "Sarah K.",
  },
  {
    id: 7,
    lead: "Anna Torres",
    company: "BrightPath",
    source: "Email Campaign",
    startDate: "2024-11-10",
    convertDate: "-",
    stage: "new",
    dealValue: "$19,200",
    daysToConvert: null,
    assignee: "Emily W.",
  },
  {
    id: 8,
    lead: "Robert Kim",
    company: "Skyline Dev",
    source: "Referral",
    startDate: "2024-07-15",
    convertDate: "2024-10-20",
    stage: "converted",
    dealValue: "$87,000",
    daysToConvert: 97,
    assignee: "John D.",
  },
];

export const crmConversionStats = {
  totalLeads: 156,
  converted: 48,
  conversionRate: 30.8,
  avgDaysToConvert: 72,
  totalDealValue: 2840000,
  conversionBySource: [
    { source: "Website", leads: 45, converted: 18, rate: 40 },
    { source: "Referral", leads: 32, converted: 14, rate: 43.8 },
    { source: "LinkedIn", leads: 28, converted: 8, rate: 28.6 },
    { source: "Cold Call", leads: 22, converted: 4, rate: 18.2 },
    { source: "Conference", leads: 15, converted: 3, rate: 20 },
    { source: "Email Campaign", leads: 14, converted: 1, rate: 7.1 },
  ],
  monthlyConversions: [
    { month: "Jul", leads: 22, converted: 6 },
    { month: "Aug", leads: 28, converted: 8 },
    { month: "Sep", leads: 25, converted: 7 },
    { month: "Oct", leads: 30, converted: 10 },
    { month: "Nov", leads: 27, converted: 9 },
    { month: "Dec", leads: 24, converted: 8 },
  ],
};

// ============ HRM Meetings Mock Data ============

export const hrmMeetings = [
  {
    id: 1,
    title: "Weekly Team Standup",
    date: "2024-12-12",
    time: "09:00 AM",
    duration: "30m",
    organizer: "Sarah Kim",
    department: "Engineering",
    attendees: 12,
    type: "recurring",
    status: "upcoming",
  },
  {
    id: 2,
    title: "Performance Review - Q4",
    date: "2024-12-13",
    time: "10:00 AM",
    duration: "1h",
    organizer: "Rachel Green",
    department: "HR",
    attendees: 3,
    type: "one_time",
    status: "upcoming",
  },
  {
    id: 3,
    title: "Budget Planning 2025",
    date: "2024-12-14",
    time: "2:00 PM",
    duration: "2h",
    organizer: "Nina Patel",
    department: "Finance",
    attendees: 8,
    type: "one_time",
    status: "upcoming",
  },
  {
    id: 4,
    title: "New Hire Orientation",
    date: "2024-12-15",
    time: "09:30 AM",
    duration: "3h",
    organizer: "Rachel Green",
    department: "HR",
    attendees: 5,
    type: "one_time",
    status: "upcoming",
  },
  {
    id: 5,
    title: "Sprint Retrospective",
    date: "2024-12-11",
    time: "3:00 PM",
    duration: "45m",
    organizer: "John Doe",
    department: "Engineering",
    attendees: 8,
    type: "recurring",
    status: "completed",
  },
  {
    id: 6,
    title: "Marketing Campaign Review",
    date: "2024-12-10",
    time: "11:00 AM",
    duration: "1h",
    organizer: "Tom Harris",
    department: "Marketing",
    attendees: 6,
    type: "one_time",
    status: "completed",
  },
  {
    id: 7,
    title: "Safety Training Session",
    date: "2024-12-16",
    time: "1:00 PM",
    duration: "2h",
    organizer: "Diana Cruz",
    department: "Operations",
    attendees: 20,
    type: "one_time",
    status: "upcoming",
  },
  {
    id: 8,
    title: "Cross-Dept Sync",
    date: "2024-12-17",
    time: "10:30 AM",
    duration: "1h",
    organizer: "Sarah Kim",
    department: "All",
    attendees: 15,
    type: "recurring",
    status: "upcoming",
  },
];

// ============ HRM Project Assignment Mock Data ============

export const hrmProjectAssignments = [
  {
    id: 1,
    project: "Website Redesign",
    employee: "John Doe",
    department: "Engineering",
    role: "Lead Developer",
    allocation: 80,
    startDate: "2024-09-01",
    endDate: "2025-03-15",
    status: "active",
  },
  {
    id: 2,
    project: "Website Redesign",
    employee: "Mike Roberts",
    department: "Design",
    role: "UI/UX Designer",
    allocation: 60,
    startDate: "2024-09-01",
    endDate: "2025-03-15",
    status: "active",
  },
  {
    id: 3,
    project: "Mobile App v2.0",
    employee: "Sarah Kim",
    department: "Engineering",
    role: "Tech Lead",
    allocation: 100,
    startDate: "2024-10-15",
    endDate: "2025-05-01",
    status: "active",
  },
  {
    id: 4,
    project: "Mobile App v2.0",
    employee: "Emily Wang",
    department: "Engineering",
    role: "Backend Developer",
    allocation: 70,
    startDate: "2024-10-15",
    endDate: "2025-05-01",
    status: "active",
  },
  {
    id: 5,
    project: "Mobile App v2.0",
    employee: "Alex Johnson",
    department: "QA",
    role: "QA Engineer",
    allocation: 50,
    startDate: "2024-11-01",
    endDate: "2025-05-01",
    status: "on_hold",
  },
  {
    id: 6,
    project: "E-commerce Platform",
    employee: "Diana Cruz",
    department: "DevOps",
    role: "DevOps Engineer",
    allocation: 40,
    startDate: "2024-08-01",
    endDate: "2025-02-28",
    status: "active",
  },
  {
    id: 7,
    project: "API Development",
    employee: "Emily Wang",
    department: "Engineering",
    role: "Backend Developer",
    allocation: 30,
    startDate: "2024-11-01",
    endDate: "2025-06-15",
    status: "active",
  },
  {
    id: 8,
    project: "Analytics Dashboard",
    employee: "John Doe",
    department: "Engineering",
    role: "Developer",
    allocation: 20,
    startDate: "2024-06-01",
    endDate: "2024-12-01",
    status: "completed",
  },
  {
    id: 9,
    project: "CRM Integration",
    employee: "Sarah Kim",
    department: "Engineering",
    role: "Architect",
    allocation: 0,
    startDate: "2025-01-15",
    endDate: "2025-04-20",
    status: "planned",
  },
  {
    id: 10,
    project: "Marketing Automation",
    employee: "Tom Harris",
    department: "Marketing",
    role: "Project Owner",
    allocation: 50,
    startDate: "2024-11-15",
    endDate: "2025-03-01",
    status: "active",
  },
];

// ============ HRM Salary Slips Mock Data ============

export const hrmSalarySlips = [
  {
    id: 1,
    employee: "John Doe",
    employeeId: "EMP-001",
    department: "Engineering",
    month: "December 2024",
    baseSalary: 7917,
    hra: 1583,
    transport: 500,
    bonus: 500,
    pf: 950,
    tax: 650,
    insurance: 250,
    netPay: 8650,
    status: "generated",
    paidDate: "2024-12-28",
  },
  {
    id: 2,
    employee: "Sarah Kim",
    employeeId: "EMP-002",
    department: "Engineering",
    month: "December 2024",
    baseSalary: 10000,
    hra: 2000,
    transport: 500,
    bonus: 800,
    pf: 1200,
    tax: 900,
    insurance: 300,
    netPay: 10900,
    status: "generated",
    paidDate: "2024-12-28",
  },
  {
    id: 3,
    employee: "Mike Roberts",
    employeeId: "EMP-003",
    department: "Design",
    month: "December 2024",
    baseSalary: 7333,
    hra: 1467,
    transport: 500,
    bonus: 300,
    pf: 880,
    tax: 550,
    insurance: 250,
    netPay: 7920,
    status: "pending",
    paidDate: "-",
  },
  {
    id: 4,
    employee: "Emily Wang",
    employeeId: "EMP-004",
    department: "Engineering",
    month: "December 2024",
    baseSalary: 7667,
    hra: 1533,
    transport: 500,
    bonus: 450,
    pf: 920,
    tax: 620,
    insurance: 250,
    netPay: 8360,
    status: "generated",
    paidDate: "2024-12-28",
  },
  {
    id: 5,
    employee: "Alex Johnson",
    employeeId: "EMP-005",
    department: "QA",
    month: "December 2024",
    baseSalary: 6500,
    hra: 1300,
    transport: 500,
    bonus: 200,
    pf: 780,
    tax: 470,
    insurance: 220,
    netPay: 7030,
    status: "pending",
    paidDate: "-",
  },
  {
    id: 6,
    employee: "Diana Cruz",
    employeeId: "EMP-006",
    department: "DevOps",
    month: "December 2024",
    baseSalary: 8750,
    hra: 1750,
    transport: 500,
    bonus: 600,
    pf: 1050,
    tax: 760,
    insurance: 250,
    netPay: 9540,
    status: "generated",
    paidDate: "2024-12-28",
  },
  {
    id: 7,
    employee: "Tom Harris",
    employeeId: "EMP-007",
    department: "Marketing",
    month: "December 2024",
    baseSalary: 6833,
    hra: 1367,
    transport: 500,
    bonus: 350,
    pf: 820,
    tax: 510,
    insurance: 250,
    netPay: 7470,
    status: "generated",
    paidDate: "2024-12-28",
  },
  {
    id: 8,
    employee: "Rachel Green",
    employeeId: "EMP-008",
    department: "HR",
    month: "December 2024",
    baseSalary: 5667,
    hra: 1133,
    transport: 500,
    bonus: 200,
    pf: 680,
    tax: 420,
    insurance: 200,
    netPay: 6200,
    status: "pending",
    paidDate: "-",
  },
];

// ============ Client/User Portal Mock Data ============

export const portalProfile = {
  id: 1,
  name: "Alex Thompson",
  email: "alex@clientcompany.com",
  phone: "+1 555-0199",
  company: "ClientCompany Inc",
  avatar: "AT",
  role: "Account Owner",
  joinDate: "2023-06-15",
  timezone: "America/New_York",
  language: "English",
  notifications: { email: true, sms: false, push: true },
};

export const portalStats = {
  activeProjects: 3,
  openTickets: 5,
  pendingInvoices: 2,
  upcomingMeetings: 4,
  totalSpent: 142500,
  spentGrowth: 18.3,
};

export const portalTickets = [
  {
    id: "PTK-001",
    subject: "Cannot upload files over 10MB",
    priority: "high",
    status: "open",
    created: "2024-12-08",
    lastUpdate: "2024-12-10",
    category: "Bug",
  },
  {
    id: "PTK-002",
    subject: "Request: Custom report builder",
    priority: "medium",
    status: "in_progress",
    created: "2024-12-05",
    lastUpdate: "2024-12-09",
    category: "Feature Request",
  },
  {
    id: "PTK-003",
    subject: "Billing discrepancy on Nov invoice",
    priority: "high",
    status: "open",
    created: "2024-12-07",
    lastUpdate: "2024-12-08",
    category: "Billing",
  },
  {
    id: "PTK-004",
    subject: "SSO login redirect loop",
    priority: "critical",
    status: "in_progress",
    created: "2024-12-03",
    lastUpdate: "2024-12-10",
    category: "Bug",
  },
  {
    id: "PTK-005",
    subject: "Add team member access",
    priority: "low",
    status: "resolved",
    created: "2024-11-28",
    lastUpdate: "2024-12-02",
    category: "Account",
  },
  {
    id: "PTK-006",
    subject: "Mobile app crashes on Android 14",
    priority: "high",
    status: "open",
    created: "2024-12-09",
    lastUpdate: "2024-12-10",
    category: "Bug",
  },
  {
    id: "PTK-007",
    subject: "API documentation outdated",
    priority: "medium",
    status: "resolved",
    created: "2024-11-25",
    lastUpdate: "2024-12-01",
    category: "Documentation",
  },
];

export const portalOrders = [
  {
    id: "ORD-001",
    product: "Enterprise License",
    quantity: 1,
    amount: "$2,400/yr",
    status: "active",
    date: "2024-01-15",
    renewal: "2025-01-15",
  },
  {
    id: "ORD-002",
    product: "Additional Storage (500GB)",
    quantity: 1,
    amount: "$49/mo",
    status: "active",
    date: "2024-03-01",
    renewal: "2025-03-01",
  },
  {
    id: "ORD-003",
    product: "Priority Support Plan",
    quantity: 1,
    amount: "$199/mo",
    status: "active",
    date: "2024-06-15",
    renewal: "2025-06-15",
  },
  {
    id: "ORD-004",
    product: "API Access Pack",
    quantity: 1,
    amount: "$99/mo",
    status: "cancelled",
    date: "2024-02-10",
    renewal: "-",
  },
  {
    id: "ORD-005",
    product: "Custom Integration Setup",
    quantity: 1,
    amount: "$5,000",
    status: "completed",
    date: "2024-04-20",
    renewal: "-",
  },
  {
    id: "ORD-006",
    product: "Training Sessions (10 pack)",
    quantity: 1,
    amount: "$1,500",
    status: "active",
    date: "2024-09-01",
    renewal: "-",
  },
];

export const portalProjects = [
  {
    id: 1,
    name: "Website Redesign",
    status: "in_progress",
    progress: 65,
    manager: "John Doe",
    startDate: "2024-09-01",
    endDate: "2025-03-15",
    milestones: 8,
    completedMilestones: 5,
  },
  {
    id: 2,
    name: "Mobile App v2.0",
    status: "in_progress",
    progress: 40,
    manager: "Sarah Kim",
    startDate: "2024-10-15",
    endDate: "2025-05-01",
    milestones: 12,
    completedMilestones: 5,
  },
  {
    id: 3,
    name: "Analytics Dashboard",
    status: "completed",
    progress: 100,
    manager: "Emily Wang",
    startDate: "2024-06-01",
    endDate: "2024-12-01",
    milestones: 6,
    completedMilestones: 6,
  },
];

export const portalInvoices = [
  {
    id: "INV-C001",
    amount: "$12,500",
    status: "paid",
    issueDate: "2024-12-01",
    dueDate: "2024-12-15",
    paidDate: "2024-12-10",
    description: "Website Redesign - Phase 2",
  },
  {
    id: "INV-C002",
    amount: "$8,200",
    status: "pending",
    issueDate: "2024-12-05",
    dueDate: "2024-12-20",
    paidDate: "-",
    description: "Monthly retainer - December",
  },
  {
    id: "INV-C003",
    amount: "$3,750",
    status: "overdue",
    issueDate: "2024-11-15",
    dueDate: "2024-11-30",
    paidDate: "-",
    description: "Mobile App - Milestone 4",
  },
  {
    id: "INV-C004",
    amount: "$25,000",
    status: "paid",
    issueDate: "2024-11-01",
    dueDate: "2024-11-15",
    paidDate: "2024-11-12",
    description: "Analytics Dashboard - Final",
  },
  {
    id: "INV-C005",
    amount: "$6,800",
    status: "pending",
    issueDate: "2024-12-08",
    dueDate: "2024-12-22",
    paidDate: "-",
    description: "Custom Integration Setup",
  },
  {
    id: "INV-C006",
    amount: "$15,400",
    status: "paid",
    issueDate: "2024-10-20",
    dueDate: "2024-11-04",
    paidDate: "2024-11-01",
    description: "Website Redesign - Phase 1",
  },
];

export const portalMeetings = [
  {
    id: 1,
    title: "Project Review - Website Redesign",
    date: "2024-12-13",
    time: "2:00 PM",
    duration: "45m",
    with: "John Doe",
    type: "video",
    status: "upcoming",
  },
  {
    id: 2,
    title: "Sprint Demo",
    date: "2024-12-14",
    time: "10:00 AM",
    duration: "30m",
    with: "Sarah Kim",
    type: "video",
    status: "upcoming",
  },
  {
    id: 3,
    title: "Budget Discussion",
    date: "2024-12-16",
    time: "3:30 PM",
    duration: "1h",
    with: "Finance Team",
    type: "in_person",
    status: "upcoming",
  },
  {
    id: 4,
    title: "Quarterly Review",
    date: "2024-12-18",
    time: "9:00 AM",
    duration: "1.5h",
    with: "Account Manager",
    type: "video",
    status: "upcoming",
  },
  {
    id: 5,
    title: "Design Walkthrough",
    date: "2024-12-10",
    time: "11:00 AM",
    duration: "30m",
    with: "Mike Roberts",
    type: "video",
    status: "completed",
  },
  {
    id: 6,
    title: "Kickoff - Phase 3",
    date: "2024-12-20",
    time: "1:00 PM",
    duration: "1h",
    with: "Project Team",
    type: "video",
    status: "upcoming",
  },
];

export const portalReviews = [
  {
    id: 1,
    project: "Analytics Dashboard",
    rating: 5,
    date: "2024-12-02",
    comment:
      "Excellent work! The dashboard exceeded our expectations. Very intuitive and fast.",
  },
  {
    id: 2,
    project: "Website Redesign - Phase 1",
    rating: 4,
    date: "2024-11-05",
    comment:
      "Great design, minor delays but overall satisfied with the quality.",
  },
  {
    id: 3,
    project: "Custom Integration",
    rating: 5,
    date: "2024-05-15",
    comment:
      "Seamless integration with our existing systems. Team was very responsive.",
  },
  {
    id: 4,
    project: "Priority Support",
    rating: 4,
    date: "2024-08-20",
    comment: "Quick response times and knowledgeable support staff.",
  },
];

export const portalChatMessages = [
  {
    id: 1,
    sender: "bot",
    message: "Hello! I'm Jevxo AI Assistant. How can I help you today?",
    timestamp: "10:00 AM",
  },
  {
    id: 2,
    sender: "user",
    message: "What's the status of my Website Redesign project?",
    timestamp: "10:01 AM",
  },
  {
    id: 3,
    sender: "bot",
    message:
      "Your Website Redesign project is currently at 65% completion. Phase 2 is in progress with 5 of 8 milestones completed. The estimated completion date is March 15, 2025. Would you like more details?",
    timestamp: "10:01 AM",
  },
  {
    id: 4,
    sender: "user",
    message: "Are there any pending invoices?",
    timestamp: "10:02 AM",
  },
  {
    id: 5,
    sender: "bot",
    message:
      "You have 2 pending invoices:\n1. INV-C002 - $8,200 (Due: Dec 20)\n2. INV-C005 - $6,800 (Due: Dec 22)\nAnd 1 overdue invoice: INV-C003 - $3,750. Would you like me to help with anything else?",
    timestamp: "10:02 AM",
  },
];

// ============ Page Management Mock Data ============

export const pagesSeoSettings = [
  {
    id: 1,
    page: "Homepage",
    url: "/",
    title: "Jevxo - Modern Business Solutions",
    description: "All-in-one CRM, HRM, and business management platform.",
    keywords: "CRM, HRM, business, management",
    score: 92,
    status: "optimized",
  },
  {
    id: 2,
    page: "About Us",
    url: "/about",
    title: "About Jevxo - Our Story",
    description:
      "Learn about Jevxo's mission to transform business management.",
    keywords: "about, company, mission",
    score: 78,
    status: "needs_improvement",
  },
  {
    id: 3,
    page: "Services",
    url: "/services",
    title: "Our Services - Jevxo",
    description: "Explore our comprehensive suite of business solutions.",
    keywords: "services, solutions, CRM, HRM",
    score: 85,
    status: "optimized",
  },
  {
    id: 4,
    page: "Blog",
    url: "/blog",
    title: "Jevxo Blog - Insights & Tips",
    description: "Stay updated with the latest business management trends.",
    keywords: "blog, insights, tips, business",
    score: 70,
    status: "needs_improvement",
  },
  {
    id: 5,
    page: "Contact",
    url: "/contact",
    title: "Contact Us - Jevxo",
    description: "Get in touch with our team for support or inquiries.",
    keywords: "contact, support, inquiry",
    score: 88,
    status: "optimized",
  },
  {
    id: 6,
    page: "Pricing",
    url: "/pricing",
    title: "Pricing Plans - Jevxo",
    description: "Choose the right plan for your business needs.",
    keywords: "pricing, plans, subscription",
    score: 95,
    status: "optimized",
  },
  {
    id: 7,
    page: "Careers",
    url: "/careers",
    title: "Careers at Jevxo",
    description: "Join our growing team of innovators.",
    keywords: "careers, jobs, hiring",
    score: 62,
    status: "poor",
  },
];

export const pagesLinks = [
  {
    id: 1,
    shortUrl: "/go/demo",
    targetUrl: "https://app.jevxo.com/demo",
    clicks: 1245,
    created: "2024-10-15",
    status: "active",
    tags: ["marketing", "demo"],
  },
  {
    id: 2,
    shortUrl: "/go/webinar",
    targetUrl: "https://zoom.us/j/123456789",
    clicks: 892,
    created: "2024-11-01",
    status: "active",
    tags: ["event", "webinar"],
  },
  {
    id: 3,
    shortUrl: "/go/docs",
    targetUrl: "https://docs.jevxo.com",
    clicks: 3421,
    created: "2024-08-20",
    status: "active",
    tags: ["documentation"],
  },
  {
    id: 4,
    shortUrl: "/go/trial",
    targetUrl: "https://app.jevxo.com/signup?plan=trial",
    clicks: 2156,
    created: "2024-09-10",
    status: "active",
    tags: ["marketing", "signup"],
  },
  {
    id: 5,
    shortUrl: "/go/survey",
    targetUrl: "https://forms.gle/abc123",
    clicks: 478,
    created: "2024-11-15",
    status: "expired",
    tags: ["feedback"],
  },
  {
    id: 6,
    shortUrl: "/go/careers",
    targetUrl: "https://jevxo.com/careers",
    clicks: 612,
    created: "2024-10-01",
    status: "active",
    tags: ["hiring"],
  },
  {
    id: 7,
    shortUrl: "/go/blackfriday",
    targetUrl: "https://jevxo.com/pricing?promo=BF2024",
    clicks: 3890,
    created: "2024-11-20",
    status: "expired",
    tags: ["marketing", "promo"],
  },
];

export const pagesBuilderPages = [
  {
    id: 1,
    name: "Landing Page - Q1 Campaign",
    slug: "/landing/q1-2025",
    status: "published",
    lastModified: "2024-12-10",
    author: "Tom Harris",
    views: 4520,
  },
  {
    id: 2,
    name: "Product Feature Showcase",
    slug: "/features",
    status: "published",
    lastModified: "2024-12-08",
    author: "Mike Roberts",
    views: 8930,
  },
  {
    id: 3,
    name: "Webinar Registration",
    slug: "/webinar/jan-2025",
    status: "draft",
    lastModified: "2024-12-09",
    author: "Tom Harris",
    views: 0,
  },
  {
    id: 4,
    name: "Case Study - CloudNine",
    slug: "/case-studies/cloudnine",
    status: "published",
    lastModified: "2024-11-25",
    author: "Sarah Kim",
    views: 2310,
  },
  {
    id: 5,
    name: "Holiday Promo Page",
    slug: "/promo/holiday-2024",
    status: "archived",
    lastModified: "2024-12-01",
    author: "Tom Harris",
    views: 12450,
  },
  {
    id: 6,
    name: "Partner Portal",
    slug: "/partners",
    status: "draft",
    lastModified: "2024-12-11",
    author: "Chris Lee",
    views: 0,
  },
];
